# Application metadata for Argo CD / ApplicationSet
# Phase 1: informational only – no behavioural change

name: intel-device-plugins-operator
path: core/node-feature-discovery/intel-device-plugins-operator
namespace: node-feature-discovery
wave: 2
env: prod
