apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-feature-discovery

helmCharts:
- name: intel-device-plugins-operator
  releaseName: intel-device-plugins-operator
  version: 0.29.0
  repo: https://intel.github.io/helm-charts


