---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-5.0.1/charts/library/common/values.schema.json
# yamllint disable-line rule:line-length

controllers:
  esphome:
    pod:
      annotations:
        # yamllint disable-line rule:line-length
        secret.reloader.stakater.com/reload: "esphome-secret,esphome-github"
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name":"macvlan-static",
            "namespace": "network",
            "ips": ["10.58.0.211"]
          }]

    initContainers:
      config-initialization:
        image:
          repository: docker.io/alpine/git
          tag: 2.54.0@sha256:fac7bc2c12aa52bff1c78a26359990e149954a60cdd5d6e20e7e009666c73e0a
        command: ["/bin/sh", "-c"]
        args:
          - |-
            set -ex
            tee /config/.kopiaignore <<!
            /.esphome
            /.code-server/logs
            /.git
            !
            cd /config
            # Need to initialise repository?
            if [ ! -d .git ] ; then
              echo "Initializing config repository from GitHub..."
              mkdir temp-dir
              git clone https://github.com/mergwyn/home-assistant-config temp-dir
              mv temp-dir/.git .
              rm -rf temp-dir
              git checkout .
            fi
        securityContext:
          runAsUser: 0

    containers:
      app:
        image:
          repository: ghcr.io/esphome/esphome
          # yamllint disable-line rule:line-length
          tag: 2026.6.5@sha256:ffe23402d169fc9b8ff29fc3c9fc13b3c47e8a53726fce4569e2280bd534c84c
        env:
          TZ: "Europe/London"
          ESPHOME_DASHBOARD_USE_PING: "true"
          DISABLE_HA_AUTHENTICATION: "true"
        resources:
          requests:
            cpu: 5m
            memory: 512Mi
          limits:
            memory: 2G

      code-server:
        dependsOn: app
        image:
          repository: ghcr.io/coder/code-server
          # yamllint disable-line rule:line-length
          tag: 4.127.0@sha256:4193b3a0c2661bce87b3cafede59e7d50e1e99e35f7c10bece7c2a7e0660c0a8
        env:
          EXTENSIONS_GALLERY: '{ "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery", "itemUrl": "https://marketplace.visualstudio.com/items" }'
        args:
          - --auth=none
          - --disable-telemetry
          - --disable-update-check
          - --user-data-dir=/config/.code-server
          - --extensions-dir=/config/.code-server
          - --port=12321
          # - --install-extension=trunk.io
          # - --install-extension=github.copilot
          - /config
        securityContext:
          runAsUser: 0
        envFrom:
          - secretRef:
              name: "{{.Release.Name}}-github"
        resources:
          requests:
            cpu: 10m
            memory: 443M
          limits:
            # cpu: null
            memory: 3G

service:
  app:
    forceRename: "{{.Release.Name}}"
    ports:
      http:
        port: 6052
  code-server:
    ports:
      http:
        port: 12321

dnsConfig:
  nameservers:
    - 10.58.0.21
    - 10.58.0.22

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: longhorn
    accessMode: ReadWriteOnce
    retain: true
    size: 5Gi
    globalMounts:
      - path: /config
  build:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /config/.esphome
        readOnly: false
  secrets:
    type: secret
    name: "{{.Release.Name}}-secret"
    globalMounts:
      - path: /config/secrets.yaml
        subPath: secrets.yaml
        readOnly: true
