k3s_token: ENC[AES256_GCM,data:knKrFOCzayhJfn4SjrWJPgMeYPb7jxhjPOyvdOF31eE=,iv:DIFH5wFINkNgAXw6GEQaZ0oproY/KikavS3LeOa9qrE=,tag:HFbe62WJriNlI4tTvXA+pg==,type:str]
sops:
    age:
        - recipient: age1kxa0h4zt4txae7wdjy5pck2jvzalmg4mrryuw3qqpzp2jl44n3tqmd0vyp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOamRUdDNjb1lWNjdhZTE4
            eHhIWTFqbFk3V2N3QXhjd0JrSENYcHFQY0hnCldJbG5MTStHaTAxTWhweXo5SW50
            dTdQWUhjbm9Odi9Lcmlaa3hnbmdkbWMKLS0tIDkxa3lnWTJkeGRCVWc0R2tPcnZK
            Mkg4cWRkbm5aTGdUN2MzODJHZTB4dEEK1/tQs/iTHTSSFyKMyLNIPa9/t7ucW5Ei
            tkk+QL3j06f6ae+CDPgULKfeciSyxl1VCR2iXGbKSGSOH3mzEj2jPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T16:39:42Z"
    mac: ENC[AES256_GCM,data:FJ+ZlpVCgArDeuFGc0hBqHts0miyjAvogBOw/Xgvs/MJ+bMjoA570fXbcxYAc+SXw6gMDCT+b04qikelC2WMlMfe7dAGU6x/1SRbK8eC6cPXLpwGO8Tx7k144oF5JbN/N9MtIlWFhr4mWcTM0Vt7n76t3rEivxMuhOWzP8euqfs=,iv:jCjT9iZV+pFsSE1S7ibkJQ8ca02h3su4DVab6zo5yF8=,tag:2dMRwhLz0r3CqehAr+PutA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
