---
apiVersion: v1
kind: Secret
metadata:
  name: helmfile-doctor-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: helmfile-doctor
type: kubernetes.io/service-account-token
