resources:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-secret
      data:
        admin.password: ENC[AES256_GCM,data:brYi9u1BM/vrXh/0BMofWtlKnEg6I9TB3AObMWSDz+9eQ7o9cAyo00DwllffTIPZbejjnkKS4tZTTVaeZAtmm566mORgiUpLiYAozknWZ6s=,iv:jtVNhdw75QerEMk9SoW1wO2z4YZCQhT+7oDzHlNcBjQ=,tag:EBusEuuzyza4uFXtIFm71w==,type:str]
        server.secretkey: ENC[AES256_GCM,data:+EPjHIdUFrHG06GUznC8AiE0FuximmYQGNWtdfaBYQTwdtIa4AZ6AU9ZQFN2Gob+gfv4g4DPQ+o8TEhI,iv:Q4WaaF9kFwq01hTHcucy8RAwRNNvq7vAK19BotV45+4=,tag:kWodvY5hulqFcqAbxC9D/A==,type:str]
sops:
    age:
        - recipient: age1kxa0h4zt4txae7wdjy5pck2jvzalmg4mrryuw3qqpzp2jl44n3tqmd0vyp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaW9xclRXY1FlN2hQTzkr
            UldBMEtHSExjVks1VFVXM1B2UjhjMGVUUEdjCkMvRGtpK1dSUE95K0JxNWFITm1G
            MkY5VXNpSUpiK3RBNXI2dEMvUEVuSjAKLS0tIGtFeVpvTGFaWTZsVU1Gd01DUmtP
            akcvMWdYSjMxWUdFeGZuMXhwb2R2dlUKWiyi13IxrY2H69m4MSWvEcmgHrRJNHWm
            9gQ3rfFrTWpdBbjockwhZ7Y0GW7Ef1PxnjZ9h+mKpqzI9eawHXzjjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T10:48:05Z"
    mac: ENC[AES256_GCM,data:dJpUGjdh73DqYkFkZeZDaWd+soU4or96gEFC6Nn/Hj+eD/5H7LuI/NSfA5i4THyJWEEBFHUo4ESVN3VRZRpCBcbBC2TRAtHN0HncJH38UXO1Cz/WAdf9UHXwEAKGuYawQ5j2pSyFt1SuIEGUBggFW49Ko9VA9ozHd+h9WaTWOog=,iv:KKFXlu65UxhHxJjeCGG+fPNiqA15nJJVfYp1vXdBpc4=,tag:hvddVFiIvVf8PUjb+AXE+g==,type:str]
    encrypted_regex: ^(data|stringData|configFile)$
    version: 3.12.2
