resources:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-secret
      data:
        admin.password: ENC[AES256_GCM,data:brYi9u1BM/vrXh/0BMofWtlKnEg6I9TB3AObMWSDz+9eQ7o9cAyo00DwllffTIPZbejjnkKS4tZTTVaeZAtmm566mORgiUpLiYAozknWZ6s=,iv:jtVNhdw75QerEMk9SoW1wO2z4YZCQhT+7oDzHlNcBjQ=,tag:EBusEuuzyza4uFXtIFm71w==,type:str]
        admin.passwordMtime: ENC[AES256_GCM,data:G7VybKeOiucXy8ht/jFCEYvDdNPfh6FwQmfP1/5Few0=,iv:Ptg1i0xDhtd8YmmE6POmLOkxuklr9RzgvNuv+LBPNWE=,tag:IjVIvRdGQBoI/Fv6JBGGWQ==,type:str]
        server.secretkey: ENC[AES256_GCM,data:+EPjHIdUFrHG06GUznC8AiE0FuximmYQGNWtdfaBYQTwdtIa4AZ6AU9ZQFN2Gob+gfv4g4DPQ+o8TEhI,iv:Q4WaaF9kFwq01hTHcucy8RAwRNNvq7vAK19BotV45+4=,tag:kWodvY5hulqFcqAbxC9D/A==,type:str]
sops:
    age:
        - recipient: age1kxa0h4zt4txae7wdjy5pck2jvzalmg4mrryuw3qqpzp2jl44n3tqmd0vyp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaW9xclRXY1FlN2hQTzkr
            UldBMEtHSExjVks1VFVXM1B2UjhjMGVUUEdjCkMvRGtpK1dSUE95K0JxNWFITm1G
            MkY5VXNpSUpiK3RBNXI2dEMvUEVuSjAKLS0tIGtFeVpvTGFaWTZsVU1Gd01DUmtP
            akcvMWdYSjMxWUdFeGZuMXhwb2R2dlUKWiyi13IxrY2H69m4MSWvEcmgHrRJNHWm
            9gQ3rfFrTWpdBbjockwhZ7Y0GW7Ef1PxnjZ9h+mKpqzI9eawHXzjjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T09:57:22Z"
    mac: ENC[AES256_GCM,data:6ANSF0rMgfcHhR4xMoaiX0ZYOQmwn3mLvTaqgfvUBGQ1h0NrIrSiPYaPE0bEZihwvVgnL4aLzqy1fIwkukzvSpdiS/Kk91ZiwS3mZ5MqY/arWYwVJMtM8lbPtNch/JbEl9VcWazonjZ5L55Y5PhejxC4cn42KNf3cuJm2Q/kIyk=,iv:VE1RXX74MbugrNndjdMQ6LT2JV5PJbq6Kw6wb17gwdY=,tag:OZ7vVlyL9BWErUMCLhDwaA==,type:str]
    encrypted_regex: ^(data|stringData|configFile)$
    version: 3.12.2
