resources:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-secret
      data:
        admin.password: ENC[AES256_GCM,data:Q7PegaEWPBTTGNkedkx9cM/p8OdZ3N8XKAHst0HcPU5SqwIAbRUECWlQQ1rnEti9zEjqxqJrUGeBDE2G,iv:xQSJRnQfbW4GtshhHHX2drg2cHZKH7oqWUvRNUhIFmE=,tag:sIzvNaKUUheTW9iwRUawAg==,type:str]
        admin.passwordMtime: ENC[AES256_GCM,data:kiXhTzCDjUmatKmtF8frrmBnfH85Dg==,iv:0u2U3ghmSRGWSdtoKRmr7U2RUUWWTzQ4C0H9HsZnfqA=,tag:ZTip0s6yozgHvRruxPzHug==,type:str]
        server.secretkey: ENC[AES256_GCM,data:WLGz6KCuPWpAqySp/j2b0O96Y6e51Tqcnaot5Ub1aJhbYSkge4dQyZfwBjA=,iv:VUDstB1/rS6opyCzD/mhGHqFFOl533Sb7HTBbGka2OU=,tag:l699syrUO3MmjnAYokXy/A==,type:str]
sops:
    age:
        - recipient: age1kxa0h4zt4txae7wdjy5pck2jvzalmg4mrryuw3qqpzp2jl44n3tqmd0vyp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaW9xclRXY1FlN2hQTzkr
            UldBMEtHSExjVks1VFVXM1B2UjhjMGVUUEdjCkMvRGtpK1dSUE95K0JxNWFITm1G
            MkY5VXNpSUpiK3RBNXI2dEMvUEVuSjAKLS0tIGtFeVpvTGFaWTZsVU1Gd01DUmtP
            akcvMWdYSjMxWUdFeGZuMXhwb2R2dlUKWiyi13IxrY2H69m4MSWvEcmgHrRJNHWm
            9gQ3rfFrTWpdBbjockwhZ7Y0GW7Ef1PxnjZ9h+mKpqzI9eawHXzjjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T15:52:19Z"
    mac: ENC[AES256_GCM,data:UYlPkf5qWFEcHKv0UvQ5GZ42xEtQtT3mZzuGOYC5K7NjB/73ns5NtM6JbpxEpuLGFCo4my4BoV2iYXTIvJQioaXlK6Ui/+v57/uB+8YRJsPJdD+QAaskDrPlDW8ekncYBRIjHjI5feeGCuQC5K3gsKw98vcWc1RTwQSjR5YIi/o=,iv:gGykaUf+oXKfy1QsKzUsulHtN1bie8vIpUFVH4mOvRU=,tag:+eKBXpOOKNBMa3PysySeAw==,type:str]
    encrypted_regex: ^(data|stringData|configFile)$
    version: 3.12.1
