apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-static
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "macvlan-static",
      "type": "ipvlan",
      "master": "br0",
      "capabilities": { "ips": true },
      "ipam": {
        "type": "host-local",
        "subnet": "10.58.0.0/24",
        "rangeStart": "10.58.0.40",
        "rangeEnd": "10.58.0.49"
      }
    }'
