---
creation_rules:
  - path_regex: /.*-sops\.yaml$
    encrypted_regex: ^(data|stringData|configFile)$
    age: >-
      age1kxa0h4zt4txae7wdjy5pck2jvzalmg4mrryuw3qqpzp2jl44n3tqmd0vyp
  - path_regex: cloudcasa/values.yaml$
    encrypted_regex: ^(clusterID|cluster_id)$
    age: >-
      age1kxa0h4zt4txae7wdjy5pck2jvzalmg4mrryuw3qqpzp2jl44n3tqmd0vyp
