apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-gitops-dev
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/mergwyn/cluster-gitops.git
      revision: main
      directories:
      - path: bootstrap/*/*
      - path: core/*/*
      - path: apps/*/*
      #- exclude: true
      #  path: apps/node-feature-discovery/*
      
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mergwyn/cluster-gitops.git
        targetRevision: main
        path: '{{path}}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - ../../settings/settings.yaml
            - ../../settings/{{ .Values.envName }}.yaml
            - values.yaml
            - values-{{ .Values.envName }}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path[1] }}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: false
        syncOptions:
        - ServerSideApply=true
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
