apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-gitops
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/mergwyn/cluster-gitops.git
      revision: main
      directories:
      - path: bootstrap/*/*
      - path: core/*/*
      - path: apps/*/*
      
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mergwyn/cluster-gitops.git
        targetRevision: main
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path[1] }}'
      ignoreDifferences:
      - kind: StatefulSet
        group: '*'
        name: mail
        jsonPointers:
        - /spec/volumeClaimTemplates
        - /spec/template/metadata/annotations
      - kind: GpuDevicePlugin
        group: '*'
        name: gpudeviceplugin
        jsonPointers:
        - /spec/resourceManager
        - /spec/tolerations
        - /metadata/annotations
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: false
        syncOptions:
        - ServerSideApply=true
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
