apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-gitops
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/mergwyn/cluster-gitops.git
      revision: main
      directories:
      - path: bootstrap/*/*
      - path: core/*/*
      - path: core/kube-system/cloudflare-tunnel-remote
        exclude: true
      - path: core/node-feature-discovery/intel-device-plugins-gpu
        exclude: true
      - path: core/node-feature-discovery/intel-device-plugins-operator
        exclude: true
      - path: core/node-feature-discovery/node-feature-discovery
        exclude: true
      - path: core/kube-system/multus
        exclude: true
      - path: apps/*/*
      - path: apps/default/home-assistant
        exclude: true
      
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mergwyn/cluster-gitops.git
        targetRevision: main
        path: '{{ path }}'
        kustomize:
          namespace: '{{ path[1] }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path[1] }}'
      ignoreDifferences:
      - kind: StatefulSet
        group: '*'
        name: mail
        jsonPointers:
        - /spec/volumeClaimTemplates
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: false
        syncOptions:
        - ServerSideApply=true
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
