# Application metadata for Argo CD / ApplicationSet
# Phase 1: informational only – no behavioural change

name: kube-vip-cloud-provider
path: base/network/kube-vip-cloud-provider
namespace: network
wave: 1
env: prod
