---
cluster:
  name: k3s-prod
  id: 1

network:
  vip: 10.58.0.30
  device: br0
  metallb:
    poolCIDR: 10.58.0.31-10.58.0.39
  homeLan:  # multus network for home LAN access
    rangeStart: 10.58.0.50
    rangeEnd: 10.58.0.59
  # VPN gateway network
  vpnGateway: 10.58.0.24
  # fixed addreses
  traefik_internal: 10.58.0.39
  plex: 10.58.0.38
  dispatcharr: 10.58.0.50
  qbittorrent: 10.58.0.51
  sabnzbd: 10.58.0.52
  prowlarr: 10.58.0.53
  radarr: 10.58.0.54
  sonarr: 10.58.0.55


# CertManager prod settings (production LE)
certManager:
  issuerName: letsencrypt-production
  acmeServer: https://acme-v02.api.letsencrypt.org/directory
