apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
- name: sabnzbd
  releaseName: sabnzbd
  repo: https://geek-cookbook.github.io/charts/
  version: 9.4.2
  valuesFile: values.yaml


