---
bases:
  - ../../../clusters/environments.yaml

apiVersions:
  - monitoring.coreos.com/v1

repositories:
  - name: traefik
    url: https://traefik.github.io/charts

releases:
  - name: traefik
    chart: traefik/traefik
    version: 40.3.0
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    values:
      - service.yaml.gotmpl
      - values.yaml
