apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
- name: multus
  releaseName: multus
  version: 3.5.2
  repo: https://geek-cookbook.github.io/charts/

#TODO parameterize multise network ranges
resources:
- nad-macvlan.yaml
- nad-ipvlan.yaml

