apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  namespace: home-assistant
  name: home-assistant-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       home-assistant
  updatePolicy:
    updateMode: "Auto"
