apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-static
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "macvlan-static",
      "type": "macvlan",
      "master": "br0",
      "capabilities": { "ips": true },
      "ipam": {
        "type": "host-local",
        "subnet": "10.58.0.0/16",
        "rangeStart": "10.58.0.40",
        "rangeEnd": "10.58.0.49"
      }
    }'

# '{
#       "cniVersion": "0.3.1",
#       "name": "macvlan-static",
#       "type": "macvlan",
#       "master": "eno2",
#       "capabilities": { "ips": true },
#       "ipam": {
#         "type": "host-local",
#         "subnet": "10.58.0.0/16",
#         "rangeStart": "10.58.0.40",
#         "rangeEnd": "10.58.0.49",
#         "gateway": "192.168.2.1"
#       }
#     }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-static
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "macvlan-static",
      "type": "ipvlan",
      "master": "br0",
      "capabilities": { "ips": true },
      "ipam": {
        "type": "host-local",
        "subnet": "10.58.0.0/16",
        "rangeStart": "10.58.0.40",
        "rangeEnd": "10.58.0.49"
      }
    }'
