clusterID: 68ed3bdd7f6f0266ee6310e4
sops:
    age:
        - recipient: age1kxa0h4zt4txae7wdjy5pck2jvzalmg4mrryuw3qqpzp2jl44n3tqmd0vyp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreUNaUWdLMkUxamRHT3dY
            RGptenRJcU0xMVF0VDdtbytYekFtMVF0MXhrCkgxN3JDOFFBZzdFRzRFenBRTTJj
            Q2o0YU5KSjBiODFrNkpXUWJza3ZtdTgKLS0tIERxY29uSWlqT1NRd0pEekEvRkVi
            czVQbmJKVHlTclE1eVlZdS83VDllVFEKHM3cWByd1u9owVW0F2efunvTEQKD65PH
            wno+p2VB3y3bsUCsPuk9x5Def05/xWAEw6T0K9BOy/Z1Ip3k2+P4Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-13T17:50:58Z"
    mac: ENC[AES256_GCM,data:7Wo24O/P2Jm66i8ha3hK9VY9noYNToxzerDhy7wVL+mAlfyb67RqEZat0uWls8hOz/EKT57Y8NuUOwWmA/m7zdXsa/XujUmoZ25+93a9M/85mSabuIZ1tfJ1FNibeUZa+QuUgg2QonNepVjzGYjDBynCf7C0XaTBEzyPMCTg7jw=,iv:H9thfb8fVpSRefy6nSHNDgWnYMpkP9LeXpUSpGnErrU=,tag:npu4YQeMKSWJYv6jmaV7Qw==,type:str]
    encrypted_regex: ^(cluster_id)$
    version: 3.10.2
