namespace: downloaders

image:
  repository: lscr.io/linuxserver/prowlarr
  tag: "1.17.2"

dnsPolicy: ClusterFirst

env:
  TZ: Europe/London
  UMASK: "002"
  PUID: "3001"
  PGID: "513"

service:
  prowlarr:
    ports:
      https:
        port: 9696

ingress:
  prowlarr:
    enabled: true
    ingressClass: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: "prowlarr.theclarkhome.com"
        paths:
          - path: /
            backend:
              name: prowlarr
              service:
                port: 9696
    tls:
      - hosts:
        - "*.theclarkhome.com"

persistence:
  config:
    enabled: true
    retain: true
    type: pvc
    storageClass: openebs-hostpath
