---
controller:
  flags:
    ignore-controller-kind: "Job,CronJob"
    on-by-default: true

dashboard:
  ingress:
    enabled: true
    ingressClass: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: "goldilocks.theclarkhome.com"
        paths:
          - path: /
            type: ImplementationSpecific
    tls:
      - hosts:
          - "*.theclarkhome.com"
