---
controllers:
  sabnzbd:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/home-operations/sabnzbd
          tag: 5.0.3@sha256:53064020792b2e21305c892c11aaa1eb32af2141cbd59119b52df226d664cd05
        env:
          SABNZBD__PORT: &port 8080
          TZ: Europe/London
        envFrom:
          - secretRef:
              name: "{{ .Release.Name }}-api-key"
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api?mode=version
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: {drop: ["ALL"]}
        resources:
          requests:
            cpu: 10m
            memory: 195Mi
          limits:
            memory: 1Gi

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 3001
    runAsGroup: 513
    fsGroup: 513
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    forceRename: "{{.Release.Name}}"
    ports:
      http:
        port: *port

persistence:
  config:
    enabled: true
    forceRename: "{{ .Release.Name }}-config"
    retain: true
    storageClass: openebs-zfspv
    accessMode: ReadWriteOnce
    size: 1Gi
  data:
    enabled: true
    existingClaim:  vpn-nfs-pvc
    globalMounts:
      - path: /data
  tmp:
    type: emptyDir
