apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-feature-discovery

helmCharts:
- name: node-feature-discovery
  releaseName: node-feature-discovery
  version: 0.16.0
  repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts



