---
repositories:
  - name: fairwinds-stable
    url: https://charts.fairwinds.com/stable
releases:
  - name: goldilocks
    chart: fairwinds-stable/goldilocks
    version: 10.2.0
    values:
      - values.yaml
    namespace: '{{ (readFile "app.yaml" | fromYaml).appNamespace }}'
