---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-spread-constraints
spec:
  background: false
  mutateExistingOnPolicyUpdate: false
  rules:
    - name: add-spread-constraints
      match:
        any:
          - resources:
              kinds:
                - Deployment
      mutate:
        patchStrategicMerge:
          spec:
            template:
              spec:
                topologySpreadConstraints:
                  - maxSkew: 1
                    topologyKey: "kubernetes.io/hostname"
                    whenUnsatisfiable: ScheduleAnyway
                    labelSelector:
                      matchLabels:
                        # Corrected JMESPath syntax for keys with dots
                        app.kubernetes.io/name: '{{ request.object.metadata.labels."app.kubernetes.io/name" || request.object.metadata.name }}'
