---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kyverno.io/clusterpolicy_v1.json
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: remove-cpu-limits-requests
spec:
  rules:
    - name: remove-cpu-limits-per-container
      match:
        any:
          - resources:
              kinds:
                - Pod
              operations:
                - CREATE
      mutate:
        foreach:
          - list: "request.object.spec.containers"
            patchesJson6902: |-
              - path: /spec/containers/{{elementIndex}}/resources/limits/cpu
                op: remove
