---
repositories:
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus-smartctl-exporter
    chart: prometheus/prometheus-smartctl-exporter
    version: 0.11.0
    values:
      - values.yaml
