---

prometheusRules:
  enabled: true
  extraLabels:
    release: kube-prometheus-stack

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack

resources:
  requests:
    cpu: 15m
    memory: 105M
  limits:
    # cpu: 21m
    memory: 105M
