---
apiVersionOverride:
  podDisruptionBudget: policy/v1

webhooksCleanup:
  enabled: true
  autoDeleteWebhooks:
    enabled: true

admissionController:
  replicas: 3
  resources:
    limits:
      cpu: null
  initContainer:
    resources:
      limits:
        cpu: null

backgroundController:
  replicas: 3
  rbac:
    clusterRole:
      extraResources:
        - apiGroups:
            - ''
          resources:
            - namespaces
          verbs:
            - create
            - update
            - delete
            - patch

crds:
  migration:
    podResources:
      limits:
        cpu: null

features:
  generateValidatingAdmissionPolicy:
    enabled: true
  PolicyExceptions:
    enabled: true


cleanupController:
  replicas: 3
reportsController:
  replicas: 3

grafana:
  enabled: true
