---
repositories:
  - name: angelnu
    url: http://angelnu.github.io/helm-charts

releases:
  - name: pod-gateway
    chart: angelnu/pod-gateway
    version: 6.5.1
    values:
      # - values.yaml
      - custom_values.yaml
      # - wg_values.yaml
