---

image:
  repository: ghcr.io/angelnu/pod-gateway
  pullPolicy: Always
  tag: v1.11.1

routed_namespaces:
  - downloaders
  - media

settings:
  NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8"
  VPN_LOCAL_CIDRS: "10.0.0.0/8"
  DNS_LOCAL_CIDRS: ""
  VPN_INTERFACE: "tun0"
  IPTABLES_NFT: "yes"
  VPN_TRAFFIC_PORT: 1194
  VPN_BLOCK_OTHER_TRAFFIC: false
  GATEWAY_ENABLE_DNSSEC: false

addons:
  vpn:
    enabled: true
    type: gluetun
    gluetun:
      image:
        repository: docker.io/qmcgaw/gluetun
        tag: v3.39.1
    # add for https://github.com/qdm12/gluetun/issues/2606
    securityContext:
      privileged: true
    env:
      TZ: Europe/London
      VPN_TYPE: openvpn
      VPN_SERVICE_PROVIDER: privatevpn
      SERVER_COUNTRIES: "United Kingdom"
      OPENVPN_VERBOSITY: 1
      VPN_INTERFACE: "tun0"
      # old vesion of variable
      FIREWALL: "off"
      # new version from 3.39.0
      FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT: "off"
      FIREWALL_DEBUG: "off"
      DOT: "off"
      FIREWALL_VPN_INPUT_PORTS: 64709
      FIREWALL_OUTBOUND_SUBNETS: "10.0.0.0/8"
      VPN_ENDPOINT_PORT: 1194
    envFrom:
      - secretRef:
          name: privatevpn-ovn

resources:
  requests:
    cpu: 40m
    memory: 53M
  limits:
    # cpu: 61m
    memory: 118M
