---
image:
  repository: ghcr.io/angelnu/pod-gateway
  pullPolicy: Always
  tag: v1.12.0

routed_namespaces:
  - test2

settings:
  # NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8"
  # VPN_LOCAL_CIDRS: "10.0.0.0/8"
  # DNS_LOCAL_CIDRS: ""
  VPN_INTERFACE: "wg0"
  IPTABLES_NFT: "yes"
  # VPN_TRAFFIC_PORT: 1194
  # VPN_BLOCK_OTHER_TRAFFIC: false
  # GATEWAY_ENABLE_DNSSEC: false

addons:
  vpn:
    enabled: true
    type: gluetun
    gluetun:
      image:
        repository: docker.io/qmcgaw/gluetun
        tag: v3.40.0
    # securityContext:
    #   privileged: true
    # volumeMounts:
    #   - mountPath: /dev/net
    #     name: dev-net
    env:
      TZ: Europe/London
      VPN_TYPE: wireguard
      VPN_SERVICE_PROVIDER: custom
      LOG_LEVEL: debug
      # OPENVPN_VERBOSITY: 1
      # VPN_INTERFACE: "tun0"
      # FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT: "off"
      # DOT: "off"
      # FIREWALL_VPN_INPUT_PORTS: 64709
      # FIREWALL_OUTBOUND_SUBNETS: "10.0.0.0/8"
      # VPN_ENDPOINT_PORT: 1194
      # added during debugging
      # VPN_PORT_FORWARDING: on
    envFrom:
      - secretRef:
          name: privatevpn-wg
    volumes:
      - name: dev-net
        hostPath:
          path: /dev/net
