---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: &name cluster-gitops-v1
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error

  generators:
    - git:
        repoURL: https://github.com/mergwyn/cluster-gitops.git
        revision: &revision main
        files:
          - path: "[0-9]*/**/app.yaml"
          - path: "**/kyverno/app.yaml"
            exclude: true

  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: wave
              operator: In
              values: ["1"]
        - matchExpressions:
            - key: wave
              operator: In
              values: ["2"]
        - matchExpressions:
            - key: wave
              operator: In
              values: ["3"]
        - matchExpressions:
            - key: wave
              operator: In
              values: ["4"]

  template:
    metadata:
      name: "{{.path.basename}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{.wave}}"
      labels:
        app.kubernetes.io/managed-by: applicationset
        applicationset: *name
        wave: "{{.wave}}"

    spec:
      project: default

      source:
        repoURL: https://github.com/mergwyn/cluster-gitops.git
        targetRevision: *revision
        path: "{{.path.path}}"
        plugin:
          name: helmfile
          env:
            - name: HELMFILE_NAMESPACE  # This passes the var to the plugin
              value: "{{.appNamespace}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.appNamespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: false
          allowEmpty: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
          - RespectIgnoreDifferences=true

      ignoreDifferences:
        - kind: StatefulSet
          group: '*'
          name: mail
          jsonPointers:
            - /spec/volumeClaimTemplates
            - /spec/template/metadata/annotations

        - kind: GpuDevicePlugin
          group: '*'
          name: gpudeviceplugin
          jsonPointers:
            - /spec/resourceManager
            - /spec/tolerations
            - /metadata/annotations

        - kind: ClusterPolicy
          group: '*'
          jsonPointers:
            - /spec/rules/0/skipBackgroundRequests

        - group: '*'
          kind: Deployment
          jqPathExpressions:
            - .spec.template.spec.hostUsers

        - group: '*'
          kind: ExternalSecret
          jqPathExpressions:
            - .spec.dataFrom[].extract.conversionStrategy
            - .spec.dataFrom[].extract.decodingStrategy
            - .spec.dataFrom[].extract.metadataPolicy

        - group: '*'
          kind: HTTPRoute
          jqPathExpressions:
            - .spec.parentRefs[].group
            - .spec.parentRefs[].kind
            - .spec.rules[].matches
            - .spec.rules[].backendRefs[].group
            - .spec.rules[].backendRefs[].kind
            - .spec.rules[].backendRefs[].weight
        # Cilium related
        - group: apps
          kind: DaemonSet
          jqPathExpressions:
            - .spec.template.metadata.annotations
        - group: ""
          kind: ConfigMap
          name: cilium-config
        # TODO check whether this can be removed
        # Added after refactor issues
        - group: ""
          kind: PersistentVolumeClaim
          jqPathExpressions:
            - .spec.volumeName
            - .spec.storageClassName
