---
repositories:
  - name: intel
    url: https://intel.github.io/helm-charts
releases:
  - name: intel-device-plugins-operator
    chart: intel/intel-device-plugins-operator
    version: 0.34.1
    values:
      - resources:
          limits:
            cpu: null
    namespace: '{{ (readFile "app.yaml" | fromYaml).appNamespace }}'
