---

config:
  general:
    TZ: Europe/London
    ALLOWED_SENDER_DOMAINS: theclarkhome.com
    DKIM_AUTOGENERATE: "yes"
  postfix:
    myhostname: relay.theclarkhome.com
    myorigin: theclarkhome.com
    smtp_tls_security_level: none

existingSecret: postfix-mail

resources:
  requests:
    cpu: 15m
    memory: 105M
  limits:
    cpu: 34m
    memory: 140M
