---
global:
  nameOverride: &app gluetun-exporter

controllers:
  *app:
    enabled: true
    type: deployment
    containers:
      *app:
        image:
          repository: ghcr.io/gluetun-exporter/standalone
          tag: latest
        env:
          GLUETUN_URL: http://pod-gateway:8000
          GLUETUN_API: PmVowHkPVfJFD2aSWeNNJj  # TODO make secret
          EXPORTER_PORT: &port 8001
          EXPORTER_ROLE: gluetun
          EXPORTER_INTERVAL: 60
          EXPORTER_DEBUG: false

        #resources:
        #  requests:
        #    cpu: 600m
        #    memory: 670M
        #    # gpu.intel.com/i915: "1"  # enable if vaapi used in sm
        #  limits:
        #    # cpu: 1100m
        #    memory: 2G
        #    # gpu.intel.com/i915: "1"  # enable if vaapi used in sm

service:
  app:
    controller: *app
    ports:
      http:
        port: *port

serviceMonitor:
  app:
    serviceName: *app
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s

rawResources:
  {}
# TODO add prometheusRule
