---

image:
  repository: ghcr.io/angelnu/pod-gateway
  pullPolicy: Always
  tag: v1.13.0

routed_namespaces:
  - downloaders
  - media
  - vpn

annotations:
  reloader.stakater.com/auto: "true"
addons:
  vpn:
    enabled: true
    type: gluetun
    gluetun:
      image:
        repository: docker.io/qmcgaw/gluetun
        tag: v3.40.0
    # add for https://github.com/qdm12/gluetun/issues/2606
    securityContext:
      privileged: true

    networkPolicy:
      enabled: true
      egress:
        - to:
            - ipBlock:
                cidr: 0.0.0.0/0
          ports:
            - port: &vpn_port 1194
              protocol: UDP
        - to:
            - ipBlock:
                cidr: 10.0.0.0/8

    env:
      TZ: Europe/London
      VPN_SERVICE_PROVIDER: privatevpn
      VPN_TYPE: openvpn
      OPENVPN_VERBOSITY: 3  # for debugging only
      DNS_KEEP_NAMESERVER: "on"  # Try with this disabled
      DOT: "off"
      FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT: "off"
      FIREWALL: "off"
      # FIREWALL_OUTBOUND_SUBNETS: "10.0.0.0/8"
      # FIREWALL_VPN_INPUT_PORTS: 64709
      # HEALTH_VPN_DURATION_ADDITION: 1800s  # for debugging only
      # HEALTH_VPN_DURATION_INITIAL: 1800s  # for debugging only
      LOG_LEVEL: debug  # for debugging only
      # SERVER_CITIES: London2
      # SERVER_COUNTRIES: "United Kingdom"
      UPDATER_PERIOD: 24h

    envFrom:
      - secretRef:
          name: privatevpn-ovn

settings:
  NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8"
  VPN_LOCAL_CIDRS: "10.0.0.0/8"
  # VPN_TRAFFIC_PORT: *vpn_port
  VPN_BLOCK_OTHER_TRAFFIC: false
  GATEWAY_ENABLE_DNSSEC: false

resources:
  requests:
    cpu: 40m
    memory: 53M
  limits:
    # cpu: 61m
    memory: 118M
