---
# Default values for cloudflare-tunnel-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cloudflare:
  secretRef:
    name: cloudflare-tunnel-secret
    accountIDKey: accountID
    tunnelNameKey: tunnelName
    apiTokenKey: apiToken

ingressClass:
  name: cloudflare-tunnel
  controllerValue: strrl.dev/cloudflare-tunnel-ingress-controller
  isDefaultClass: false

replicaCount: 2

resources:
  limits:
    cpu: null

image:
  repository: cr.strrl.dev/strrl/cloudflare-tunnel-ingress-controller
  tag: 0.0.18

cloudflared:
  image:
    repository: cloudflare/cloudflared
    pullPolicy: IfNotPresent
    tag: 2025.10.0@sha256:396cd2e6f021275ad09969a1b4f1a7e62ca5349fde62781ce082bb2c18105c70
  replicaCount: 2

# cloudflaredServiceMonitor:
#   create: false
#   jobLabel: ""
#   interval: ""
#   scrapeTimeout: ""
#   honorLabels: false
#   metricRelabelings: []
#   relabelings: []
#   labels: {}
#   scheme: http
