# yaml-language-server: $schema=https://json.schemastore.org/helmfile
---
bases:
  - ../../../clusters/environments.yaml

repositories:
  - name: kyverno
    url: https://kyverno.github.io/kyverno/

releases:
  - name: kyverno
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    chart: kyverno/kyverno
    version: 3.8.1
    force: true
    values:
      - values.yaml

  - name: kyverno-policies-custom
    chart: ./policies
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    needs:
      - kyverno
    values:
      - validationFailureAction: Enforce
