# yaml-language-server: $schema=https://json.schemastore.org/helmfile
---
bases:
  - ../../../common/base.yaml

repositories:
  - name: kyverno
    url: https://kyverno.github.io/kyverno/

releases:
  - name: kyverno
    chart: kyverno/kyverno
    version: 3.9.1
    inherit:
    - template: namespace
    force: true
    values:
      - values.yaml

  - name: kyverno-policies
    needs:
      - kyverno
    inherit:
    - template: raw
    - template: cluster-scoped
