---

---
apiVersionOverride:
  podDisruptionBudget: policy/v1

webhooksCleanup:
  enabled: true
  autoDeleteWebhooks:
    enabled: true

admissionController:
  serviceMonitor:
    enabled: true
  replicas: 3
  resources:
    limits:
      cpu: null
  initContainer:
    resources:
      limits:
        cpu: null
  rbac:
    coreClusterRole:
      extraResources:
        - apiGroups:
            - velero.io
          resources:
            - backups
            - schedules
          verbs:
            - get
            - list
            - watch
            - update
            - patch
        - apiGroups:
            - ''
          resources:
            - persistentvolumes
            - persistentvolumeclaims
          verbs:
            - get
            - create
            - update
            - list

backgroundController:
  serviceMonitor:
    enabled: true
  replicas: 3
  rbac:
    coreClusterRole:
      extraResources:
        - apiGroups:
            - ''
          resources:
            - namespaces
          verbs:
            - create
            - update
            - delete
            - patch
        - apiGroups:
            - ''
          resources:
            - persistentvolumes
            - persistentvolumeclaims
          verbs:
            - get
            - create
            - update
            - list
        - apiGroups:
            - velero.io
          resources:
            - backups
            - schedules
          verbs:
            - get
            - list
            - watch
            - update
            - patch

features:
  generateValidatingAdmissionPolicy:
    enabled: true
  PolicyExceptions:
    enabled: true

cleanupController:
  serviceMonitor:
    enabled: true
  replicas: 3

reportsController:
  serviceMonitor:
    enabled: true
  replicas: 3

grafana:
  enabled: true
