---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-5.0.1/charts/library/common/values.schema.json
controllers:
  qbittorrent:
    annotations:
      reloader.stakater.com/auto: "true"
      # Set a minimum memory floor for the VPA
      goldilocks.fairwinds.com/vpa-min-memory: "4500Mi"
      # Optional: Set a max if you want to prevent it from runaway leaks
      goldilocks.fairwinds.com/vpa-max-memory: "6Gi"

    containers:
      app:
        image:
          repository: ghcr.io/home-operations/qbittorrent
          tag: 5.2.1@sha256:8d58d9ad18a1fb5e556e68bde7ac06046847cc97069257f01d2e1ec0d27ff019
        env:
          QBT_WEBUI_PORT: &port 8080
          QBT_TORRENTING_PORT: 51478
          TZ: Europe/London
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/v2/app/version
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 450m
            memory: 4500Mi
          limits:
            memory: 6Gi

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 3001
    runAsGroup: 513
    fsGroup: 513
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    forceRename: "{{.Release.Name}}"
    ports:
      http:
        port: *port

persistence:
  config:
    enabled: true
    retain: true
    forceRename: "{{.Release.Name}}-config"
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
  data:
    enabled: true
    existingClaim: vpn-nfs-pvc
    globalMounts:
      - path: /data
  tmp:
    type: emptyDir
