
---
global:
  # -- Set an override for the prefix of the fullname
  nameOverride: streammaster
  # -- Set the entire name definition
  fullnameOverride:
  # -- Set additional global labels. Helm templates can be used.
  labels: {}
  # -- Set additional global annotations. Helm templates can be used.
  annotations: {}

controllers:
  streammaster:
    enabled: true
    type: deployment
    containers:
      streammaster:
        image:
          repository: senexcrenshaw/streammaster
          tag: channels-0.15.0.51
#        env:
#          PUID: 1000
#          PGID: 1000
#          POSTGRES_USER: 'sm'
#          ASPNETCORE_ENVIRONMENT: "Development"
#          ASPNETCORE_Kestrel__Certificates__Default__Password: "password"
#          ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
#          ASPNETCORE_URLS: "https://+:443;http://+:80"
#          STREAMMASTER_BASEHOSTURL: "http://localhost:7095"

service:
  # Configure a service for the main application
  streammaster:
    controller: streammaster
    type: ClusterIP
    ports:
      http:
        port: 7095
      #7096:
      #  port: 7096

defaultPodOptions:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - foxtrot

ingress:
  streammaster:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: &host "streammaster.theclarkhome.com"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: streammaster
              port: http
    tls:
      - hosts:
          - '*.theclarkhome.com'

persistence:
  config: # streammaster-claim0
    type: persistentVolumeClaim
    storageClass: openebs-zfspv
    accessMode: ReadWriteOnce
    retain: true
    size: 1G
    globalMounts:
      - path: /root/.streammaster

  logos: #streammaster-claim1
    type: persistentVolumeClaim
    storageClass: openebs-zfspv
    accessMode: ReadWriteOnce
    size: 1G
    retain: true
    globalMounts:
      - path: /root/.streammaster/tv-logos

#  https: #streammaster-claim2
#    accessMode: ReadWriteOnce
#    size: 1G
#    globalMounts:
#      - path: /https
#    
