image:
  repository: lscr.io/linuxserver/sonarr
  tag: "4.0.0"

dnsPolicy: ClusterFirst

env:
  TZ: Europe/London
  UMASK: "002"
  PUID: "3001"
  PGID: "513"

service:
  sonarr:
    ports:
      https:
        port: 8989

ingress:
  sonarr:
    enabled: true
    ingressClass: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: "sonarr.theclarkhome.com"
        paths:
          - path: /
            backend:
              name: sonarr
              service:
                port: 8989
    tls:
      - hosts:
        - "*.theclarkhome.com"

persistence:
  config:
    enabled: true
    retain: true
    storageClass: appdata-storage
  data:
    enabled: true
    type: nfs
    server: 10.58.0.12
    path: /srv/media


