---
image:
  repository: lscr.io/linuxserver/sonarr
  tag: "4.0.15"

dnsPolicy: ClusterFirst

env:
  TZ: Europe/London
  UMASK: "002"
  PUID: "3001"
  PGID: "513"

service:
  sonarr:
    ports:
      https:
        port: 8989

ingress:
  internal:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: "sonarr.theclarkhome.com"
        paths:
          - path: /
            backend:
              name: sonarr
              service:
                port: 8989
    tls:
      - hosts:
          - "*.theclarkhome.com"

  external:
    enabled: true
    ingressClassName: cloudflare-tunnel
    annotations:
      cloudflare-tunnel-ingress-controller.strrl.dev/backend-protocol: http
    hosts:
      - host: "sonarr.theclarkhome.com"
        paths:
          - path: /
            backend:
              name: sonarr

persistence:
  config:
    enabled: true
    retain: true
    storageClass: openebs-zfspv
  data:
    enabled: true
    type: nfs
    server: 10.58.0.12
    path: /srv/media

resources:
  requests:
    cpu: 10m
    memory: 324M
  limits:
    # cpu: 29m
    memory: 2300M
