---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile

repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts/

releases:
  - name: external-secrets
    chart: oci://ghcr.io/external-secrets/charts/external-secrets
    version: 0.19.2
    values:
      - values.yaml

  - name: bitwarden-store
    chart: bedag/raw
    version: 2.0.0
    values:
      - bitwarden-store.yaml
