---
image:
  repository: cloudflare/cloudflared
  tag: 2025.8.0

# tunnel:
#   token:
#     secretName: cloudflare-token-secret

replicaCount: 2

resources:
  requests:
    cpu: 15m
    memory: 105M
  limits:
    # cpu: 15m
    memory: 105M
