# Application metadata for Argo CD / ApplicationSet
# Phase 1: informational only – not yet consumed

name: zigbee2mqtt
path: apps/home-assistant/zigbee2mqtt
namespace: home-assistant
wave: 3
env: prod
