---
image:
  repository: koenkk/zigbee2mqtt
  tag: 1.42.0

env:
  - name: TZ
    value: "Europe/London"
  - name: ZIGBEE2MQTT_DATA
    value: "/data"
  - name: ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_DISCOVERY_TOPIC
    value: "homeassistant"
  - name: ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_STATUS_TOPIC
    value: "homeassistant/status"
  - name: ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN
    value: "ISO_8601"
  - name: ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL
    value: "info"
  - name: ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT
    value: '["console"]'
  - name: ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY
    value: "GENERATE"
  - name: ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API
    value: true
  - name: ZIGBEE2MQTT_CONFIG_FRONTEND_PORT
    value: 8080
  - name: ZIGBEE2MQTT_CONFIG_FRONTEND_URL
    value: "https://zigbee2mqtt.theclarkhome.com"
  - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED
    value: true
  - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_DISCOVERY_TOPIC
    value: "homeassistant"
  - name: ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC
    value: "zigbee2mqtt"
  - name: ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION
    value: true
  - name: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mqtt-credentials
        key: MQTT_PASSWORD
  - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
    value: "mqtt://mosquitto:1883"
  - name: ZIGBEE2MQTT_CONFIG_MQTT_USER
    valueFrom:
      secretKeyRef:
        name: mqtt-credentials
        key: MQTT_USER
  - name: ZIGBEE2MQTT_CONFIG_PERMIT_JOIN
    value: false
  - name: ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER
    value: "ezsp"
  - name: ZIGBEE2MQTT_CONFIG_SERIAL_PORT
    value: "mqtt://10.58.0.201:1883"

service:
  main:
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    ingressClass: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: "zigbee2mqtt.theclarkhome.com"
        paths:
          - path: /
            pathType: Prefix
            backend:
              name: main
              service:
                port: 8080
    tls:
      - hosts:
          - "*.theclarkhome.com"

persistence:
  data:
    enabled: true
    mountPath: /data
    type: pvc
    storageClass: openebs-zfspv
    accessMode: ReadWriteOnce
    size: 1Gi

resources:
  requests:
    cpu: 50m
    memory: 384M
  limits:
    memory: 384M
