---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kyverno.io/clusterpolicy_v1.json
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: goldilocks-tiered-management
spec:
  rules:
    # --- STEP 1: AUTO-PILOT FOR SELECTED NAMESPACES ---
    - name: enable-auto-vpa-for-apps
      match:
        any:
          - resources:
              kinds:
                - Namespace
              names: &autons
                - default
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              goldilocks.fairwinds.com/enabled: "true"
              goldilocks.fairwinds.com/vpa-update-mode: "InPlaceOrRecreate"

    # --- STEP 2: OBSERVABILITY ONLY FOR ALL OTHER NAMESPACES ---
    - name: enable-vpa-guidance-only
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              names: *autons
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              goldilocks.fairwinds.com/enabled: "true"
              goldilocks.fairwinds.com/vpa-update-mode: "Off"
