---
controllers:
  qbittorrent:
    annotations:
      reloader.stakater.com/auto: "true"
      # Set a minimum memory floor for the VPA
      goldilocks.fairwinds.com/vpa-min-memory: "4500Mi"
      # Optional: Set a max if you want to prevent it from runaway leaks
      goldilocks.fairwinds.com/vpa-max-memory: "6Gi"

    containers:
      app:
        image:
          repository: ghcr.io/home-operations/qbittorrent
          tag: 5.1.4@sha256:bb82ad6668f8eda1d0fcce6c1341498bfa879155bb1295cd9d314a2c35c07a01
        env:
          QBT_WEBUI_PORT: &port 8080
          QBT_TORRENTING_PORT: 51478
          TZ: Europe/London
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/v2/app/version
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 22m
            memory: 4500Mi
          limits:
            memory: 6Gi"

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 3001
    runAsGroup: 513
    fsGroup: 513
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    forceRename: "{{.Release.Name}}"
    ports:
      http:
        port: *port

persistence:
  config:
    enabled: true
    retain: true
    forceRename: "{{.Release.Name}}-config"
    storageClass: openebs-zfspv
    accessMode: ReadWriteOnce
    size: 1Gi
  data:
    enabled: true
    type: nfs
    server: 10.58.0.12
    path: /srv/media
    globalMounts:
      - path: /data
  tmp:
    type: emptyDir
