---
bases:
  - ../../../clusters/environments.yaml

repositories:
  - name: cilium
    url: https://helm.cilium.io/

releases:
  - name: cilium
    chart: cilium/cilium
    version: 1.20.1
    values:
      - values.yaml.gotmpl
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
