---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile

bases:
  - ../../../clusters/environments.yaml

repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts/

releases:
  - name: coredns
    namespace: kube-system
    chart: bedag/raw
    values:
      - resources:
          - apiVersion: helm.cattle.io/v1
            kind: HelmChartConfig
            metadata:
              name: coredns
              namespace: kube-system
            spec:
              valuesContent: |-
                replicaCount: 3
                tolerations:
                  - key: "node-role.kubernetes.io/control-plane"
                    operator: "Exists"
                    effect: "NoSchedule"
                topologySpreadConstraints:
                  - maxSkew: 1
                    topologyKey: kubernetes.io/hostname
                    whenUnsatisfiable: DoNotSchedule
                    labelSelector:
                      matchLabels:
                        k8s-app: kube-dns
                podDisruptionBudget:
                  enabled: true
                  minAvailable: 2
