---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-5.0.1/charts/library/common/values.schema.json
global:
  nameOverride: predbat

controllers:
  predbat:
    annotations:
      reloader.stakater.com/auto: "true"
    enabled: true
    type: deployment

    defaultContainerOptions:
      resources:
        requests:
          cpu: 250m
          memory: 260Mi
        limits:
          memory: 512Mi

    containers:
      app:
        image:
          repository: nipar44/predbat_addon
          tag: alpine-v8.40.5@sha256:2ca07b7af8d1cc9e442016167e1b43648a7eae37e8d400bd0d53f549c15baf66
        env:
          TZ: "Europe/London"

service:
  app:
    forceRename: "{{.Release.Name}}"
    ports:
      http:
        port: 5052

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: longhorn
    accessMode: ReadWriteOnce
    retain: true
    size: 1Gi
    globalMounts:
      - path: /config
