---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-5.0.1/charts/library/common/values.schema.json
global:
  nameOverride: predbat

controllers:
  predbat:
    annotations:
      reloader.stakater.com/auto: "true"
    enabled: true
    type: deployment

    defaultContainerOptions:
      resources:
        requests:
          cpu: 250m
          memory: 260Mi
        limits:
          memory: 512Mi

    containers:
      app:
        image:
          repository: nipar44/predbat_addon
          tag: alpine-v8.47.7@sha256:5c44c1d0c58a2205eb1e8bdd2c446f6db651aac66a7ff81d700eb58a5d2f2ac1
        env:
          TZ: "Europe/London"

service:
  app:
    forceRename: "{{.Release.Name}}"
    ports:
      http:
        port: 5052

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: longhorn
    accessMode: ReadWriteOnce
    retain: true
    size: 1Gi
    globalMounts:
      - path: /config
