---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile

bases:
  - ../../../clusters/environments.yaml

repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts/

releases:
  - name: coredns-custom
    chart: bedag/raw
    version: 2.0.2
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    values:
      - resources:
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: coredns-custom
              namespace: kube-system
            data:
              forward.override: |
                forward . 1.1.1.1 8.8.8.8 {
                  force_tcp
                }
