---
releases:

  - name: multus-cni
    chart: oci://registry-1.docker.io/bitnamicharts/multus-cni
    version: 2.2.2
    values:
      - multus-values.yaml.gotmpl

  - name: whereabouts
    chart: oci://registry-1.docker.io/bitnamicharts/whereabouts
    version: 1.2.2
    values:
      - whereabouts-values.yaml
