---
extraDeploy:
  - apiVersion: "k8s.cni.cncf.io/v1"
    kind: NetworkAttachmentDefinition
    metadata:
      name: macvlan-static
    spec:
      config: '{
          "cniVersion": "0.3.1",
          "name": "macvlan-static",
          "type": "macvlan",
          "master": "br0",
          "capabilities": { "ips": true },
          "ipam": {
            "type": "host-local",
            "subnet": "10.58.0.0/16",
            "rangeStart": "10.58.0.40",
            "rangeEnd": "10.58.0.48"
          }
        }'

  - apiVersion: "k8s.cni.cncf.io/v1"
    kind: NetworkAttachmentDefinition
    metadata:
      name: ipvlan-static
    spec:
      config: '{
          "cniVersion": "0.3.1",
          "name": "macvlan-static",
          "type": "ipvlan",
          "master": "br0",
          "capabilities": { "ips": true },
          "ipam": {
            "type": "host-local",
            "subnet": "10.58.0.0/16",
            "rangeStart": "10.58.0.40",
            "rangeEnd": "10.58.0.48"
          }
        }'

  - apiVersion: "k8s.cni.cncf.io/v1"
    kind: NetworkAttachmentDefinition
    metadata:
      name: whereabouts-ha
    spec:
      config: '{
          "cniVersion": "0.3.1",
          "name": "ha-ipvlan",
          "type": "ipvlan",
          "master": "br0",
          "mode": "bridge",
          "ipam": {
            "type": "whereabouts",
            "range": "10.58.0.49/28"
          }
        }'
