resources:
  - apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: &secret helmfile-doctor-env
    spec:
      refreshInterval: 1h
      secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden
      target:
        name: *secret
        creationPolicy: Owner
        template:
          engineVersion: v2
          data:
            HELMFILE_LLM_API_KEY: '{{ (.openwebui | fromYaml).doctor }}'

      data:
        - secretKey: openrouter
          remoteRef:
            key: openrouter_api_key
