---
controllers:
  prowlarr:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/home-operations/prowlarr
          tag: 2.3.6@sha256:da6b1f914ad22778c347d554a59b6e40110f654b40528c8de516616382db5148
        env:
          PROWLARR__APP__INSTANCENAME: "{{ .Release.Name }}"
          PROWLARR__APP__THEME: dark
          PROWLARR__AUTH__METHOD: External
          PROWLARR__AUTH__REQUIRED: DisabledForLocalAddresses
          PROWLARR__LOG__DBENABLED: "False"
          PROWLARR__LOG__LEVEL: info
          PROWLARR__SERVER__PORT: &port 9696
          PROWLARR__UPDATE__BRANCH: develop
          TZ: Europe/London
        envFrom:
          - secretRef:
              name: "{{ .Release.Name }}-api-key"
#        lifecycle:
#          postStart:
#            exec:
#              command:
#              - /bin/sh
#              - -c
#              - "until grep -q '172.16.0.1' /etc/resolv.conf; do sleep 1; done; echo 'RESOLV_CONF=no' >> /etc/udhcpc/udhcpc.conf; sed -i 's/ndots:5/ndots:1/' /etc/resolv.conf"
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities: {drop: ["ALL"]}
        resources:
          requests:
            cpu: 100m
            memory: 183Mi
          limits:
            memory: 512Mi

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 3001
    runAsGroup: 513
    fsGroup: 513
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    forceRename: "{{.Release.Name}}"
    ports:
      http:
        port: *port

persistence:
  config:
    enabled: true
    forceRename: "{{ .Release.Name }}-config"
    retain: true
    storageClass: openebs-zfspv
    accessMode: ReadWriteOnce
    size: 2Gi
  config-cache:
    storageClass: openebs-zfspv
    accessMode: ReadWriteOnce
    size: 2Gi
    globalMounts:
      - path: /config/MediaCover
  data:
    enabled: true
    existingClaim: vpn-nfs-pvc
    globalMounts:
      - path: /data
  tmp:
    type: emptyDir
