---

image:
  repository: ghcr.io/angelnu/pod-gateway
  tag: v1.13.0
webhook:
  controllerAnnotations:
    reloader.stakater.com/auto: "true"

addons:
  vpn:
    enabled: true
    type: gluetun
    gluetun:
      image:
        repository: docker.io/qmcgaw/gluetun
        tag: v3.40.0

    env:
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
      VPN_INTERFACE: wg0
      DOT: "off"
      FIREWALL: "off"
      # SERVER_COUNTRIES: "United Kingdom"

      # FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT: "off"
      # DNS_KEEP_NAMESERVER: "on"
      # HEALTH_VPN_DURATION_INITIAL: "600s"
      # LOG_LEVEL: debug
      # WIREGUARD_IMPLEMENTATION: userspace

    envFrom:
      - secretRef:
          name: privatevpn-wg

#    livenessProbe:
#      exec:
#        command:
#          - sh
#          - -c
#          - if [ $(wget -q -O- https://ipinfo.io/country) == 'UK' ]; then exit 0; else exit $?; fi
#      initialDelaySeconds: 30
#      periodSeconds: 60
#      failureThreshold: 3

    networkPolicy:
      enabled: true

      egress:
        - to:
            - ipBlock:
                cidr: 0.0.0.0/0
          ports:
            # VPN traffic
            - port: &vpn_port 3389
              protocol: UDP
        - to:
            - ipBlock:
                cidr: 10.0.0.0/8

routed_namespaces:
  - vpn

settings:
  # -- If using a VPN, interface name created by it
  VPN_INTERFACE: wg0
  # -- Prevent non VPN traffic to leave the gateway
  VPN_BLOCK_OTHER_TRAFFIC: true
  # -- If VPN_BLOCK_OTHER_TRAFFIC is true, allow VPN traffic over this port
  VPN_TRAFFIC_PORT: *vpn_port
  # -- Traffic to these IPs will be send through the K8S gateway
  VPN_LOCAL_CIDRS: "10.0.0.0/8 192.168.0.0/16"
