---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json

controllers:
  matterhub:
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name":"macvlan-static",
            "namespace": "network",
            "ips": ["10.58.0.213"]
          }]
    containers:
      app:
        image:
          repository: ghcr.io/t0bst4r/home-assistant-matter-hub
          tag: 3.0.0-alpha.72

        env:
          TZ: "Europe/London"
          HAMH_LOG_LEVEL: debug
          HAMH_WEB_PORT: &port 8482
          HAMH_STORAGE_LOCATION: /data
          HAMH_MDNS_NETWORK_INTERFACE: br0
          HAMH_HOME_ASSISTANT_URL: http://home-assistant:8123

        envFrom:
          - secretRef:
              name: home-assistant-matter-hub-secret

        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false

        securityContext:
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - "ALL"
        resources:
          requests:
            cpu: 15m
            memory: 145M
          limits:
            memory: 256M


defaultPodOptions:
  hostNetwork: true
  hostPID: true
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile: {type: RuntimeDefault}

service:
  app:
    forceRename: "{{.Release.Name}}"
    ports:
      http:
        port: *port

ingress:
  app:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: "{{.Release.Name}}.{{.Values.global.domain}}"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - "*.{{.Values.global.domain}}"

persistence:
  data:
    type: persistentVolumeClaim
    storageClass: openebs-zfspv
    accessMode: ReadWriteOnce
    retain: true
    size: 1G
    globalMounts:
      - path: /data

  tmp:
    type: emptyDir
    medium: Memory
    globalMounts:
      - path: /tmp
