---
image:
  repository: cloudflare/cloudflared
  tag: 2026.3.0@sha256:6b599ca3e974349ead3286d178da61d291961182ec3fe9c505e1dd02c8ac31b0

# tunnel:
#   token:
#     secretName: cloudflare-token-secret

replicaCount: 2

resources:
  requests:
    cpu: 15m
    memory: 105M
  limits:
    # cpu: 15m
    memory: 105M
