repositories:
- name: geek-cookbook
  url: https://geek-cookbook.github.io/charts/
- name: incubator
  url: https://charts.helm.sh/incubator

releases:
- name: plex
  chart: geek-cookbook/plex
  version: 6.4.3
  values:
  - values.yaml
- name: plex-vpa
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: autoscaling.k8s.io/v1
      kind: VerticalPodAutoscaler
      metadata:
        namespace: default
        name: plex-vpa
        labels:
          app.kubernetes.io/instance: plex
          app.kubernetes.io/name: plex
      spec:
        targetRef:
          apiVersion: "apps/v1"
          kind:       Deployment
          name:       plex
        updatePolicy:
          updateMode: "Auto"

