repositories:
- name: geek-cookbook
  url: https://geek-cookbook.github.io/charts/

releases:
- name: plex
  chart: geek-cookbook/plex
  version: 6.4.3
  values:
  - values.yaml
#  - resources:
#    - apiVersion: autoscaling.k8s.io/v1
#      kind: VerticalPodAutoscaler
#      metadata:
#        namespace: default
#        name: plex-vpa
#      spec:
#        targetRef:
#          apiVersion: "apps/v1"
#          kind:       Deployment
#          name:       plex
#        updatePolicy:
#          updateMode: "Auto"
#
