---
image:
  repository: plexinc/pms-docker
  tag: '1.41.0.8994-f2c27da23'

env:
  PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR: "/config"
  PLEX_CLAIM: "claim-LufEVYTg9R29o2qzZsLA"
  ALLOWED_NETWORKS: "10.0.0.0/8"
  # ADVERTISE_IP: ""
  PLEX_GID: "513"
  PLEX_PASS: "yes"
  PLEX_UID: "3001"
  TZ: Europe/London
  UMASK: "002"

service:
  main:
    type: LoadBalancer
    loadBalancerIP: "10.58.0.34"
    ports:
      https:
        protocol: HTTPS
        port: 32400
        targetPort: 32400

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - foxtrot

resources:
  requests:
    cpu: 15m
    memory: 351M
    gpu.intel.com/i915: "1"
  limits:
    cpu: 1947m
    memory: 1024M
    gpu.intel.com/i915: "1"

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /opt/appdata/plex
  data:
    enabled: true
    type: hostPath
    hostPath: /srv/media
    mountPath: /data
