---
repositories:
  - name: fairwinds-stable
    url: https://charts.fairwinds.com/stable

releases:
  - name: goldilocks
    chart: fairwinds-stable/goldilocks
    version: 10.0.0
    values:
      - values.yaml
