---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json

controllers:
  radarr:
    annotations:
      reloader.stakater.com/auto: "true"
    initContainers:
      create-kopiaignore:
        image:
          repository: busybox
          tag: latest
        command:
          - sh
          - -c
          - mkdir -p /config/MediaCover && echo '*' > /config/MediaCover/.kopiaignore
    containers:
      app:
        image:
          repository: ghcr.io/home-operations/radarr
          tag: 6.2.1@sha256:09979c77f9be3f324c133e1e73fea2b5c7eed37b586ed7c8a8a60c9b6932f175
        env:
          RADARR__APP__INSTANCENAME: "{{ .Release.Name }}"
          RADARR__APP__THEME: dark
          RADARR__AUTH__METHOD: External
          RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
          RADARR__LOG__DBENABLED: "False"
          RADARR__LOG__LEVEL: info
          RADARR__SERVER__PORT: &port 7878
          # RADARR__UPDATE__BRANCH: develop
          TZ: Europe/London
        envFrom:
          - secretRef:
              name: "{{ .Release.Name }}-api-key"
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: {drop: ["ALL"]}
        resources:
          requests:
            cpu: 100m
            memory: 272M
          limits:
            memory: 429M

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 3001
    runAsGroup: 513
    fsGroup: 513
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    forceRename: "{{.Release.Name}}"
    ports:
      http:
        port: *port

persistence:
  config:
    enabled: true
    forceRename: "{{ .Release.Name }}-config"
    retain: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 2Gi
  data:
    enabled: true
    existingClaim: vpn-nfs-pvc
    globalMounts:
      - path: /data
  tmp:
    type: emptyDir
