---
cluster:
  name: k3s-prod
  domain: theclarkhome.com
  defaultGateway: 10.0.0.1
  region: uk
  timezone: Europe/London

network:
  podCIDR: 10.42.0.0/16
  serviceCIDR: 10.43.0.0/16
  subnet: 10.58.0
  metallb:
    # TODO kube-vip is currently on .32 - migrate
    poolCIDR: 10.58.0.33-10.58.0.39

platform:
  ingressClass: traefik
  storageClass:
    default: openebs-hostpath
