---
repositories:
  - name: vmware-tanzu
    url: https://vmware-tanzu.github.io/helm-charts

releases:
  - name: velero
    chart: oci://ghcr.io/vmware-tanzu/charts/velero
    version: 9.0.1
    values:
      - values.yaml
