---
crds:
  enabled: true

extraArgs:
  - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
  - --dns01-recursive-nameservers-only

podDnsConfig:
  nameservers:
    - "1.1.1.1"
    - "9.9.9.9"

resources:
  requests:
    cpu: 15m
    memory: 105M
  limits:
    # cpu: 21m
    memory: 122M

webhook:
  resources:
    requests:
      cpu: 15m
      memory: 105M
    limits:
      # cpu: 21m
      memory: 105M

cainjector:
  resources:
    requests:
      cpu: 15m
      memory: 105M
    limits:
      # cpu: 21m
      memory: 122M
