---
repositories:
  - name: cloudflare
    url: https://cloudflare.github.io/helm-charts

releases:
  - name: cloudflare-tunnel
    chart: cloudflare/cloudflare-tunnel
    version: 0.3.2
    values:
      - values.yaml
