---
repositories:
  - name: openebs
    url: https://openebs.github.io/openebs
  - name: bedag
    url: https://bedag.github.io/helm-charts/
releases:
  - name: openebs
    chart: openebs/openebs
    version: 4.4.0
    values:
      - values.yaml
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
  - name: openebs-extra
    chart: bedag/raw
    version: 2.0.2
    values:
      - resources:
          - apiVersion: storage.k8s.io/v1
            kind: StorageClass
            metadata:
              name: openebs-zfspv
            parameters:
              recordsize: "4k"
              compression: "lz4"
              dedup: "off"
              fstype: "zfs"
              shared: "yes"
              poolname: "rpool/zfspv"
            provisioner: zfs.csi.openebs.io
            allowVolumeExpansion: true
            volumeBindingMode: WaitForFirstConsumer
          - apiVersion: snapshot.storage.k8s.io/v1
            kind: VolumeSnapshotClass
            metadata:
              name: openebs-zfspv-snapshot
              annotations:
                snapshot.storage.kubernetes.io/is-default-class: "true"
              labels:
                velero.io/csi-volumesnapshot-class: "true"
            driver: zfs.csi.openebs.io
            deletionPolicy: Delete
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
