---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile

helmDefaults:
  wait: true
  waitForJobs: true

bases:
  - ../../../clusters/environments.yaml

apiVersions:
  - "monitoring.coreos.com/v1/ServiceMonitor"

repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts/
  - name: external-secrets
    url: https://charts.external-secrets.io/

releases:
  - name: external-secrets
    chart: external-secrets/external-secrets
    version: 2.2.0
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    values:
      - values.yaml

  - name: bitwarden-access-token
    chart: bedag/raw
    version: 2.0.2
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    secrets:
      - bitwarden-access-token-sops.yaml

  - name: bitwarden-store
    chart: bedag/raw
    version: 2.0.2
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    values:
      - bitwarden-store.yaml
    needs:
      - bitwarden-access-token
      - external-secrets
