---
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts/

releases:
  - name: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    version: 78.2.0
    values:
      - values.yaml
      - externalsecret.yaml
