---
- name: Get kubeconfig from first node
  delegate_to: localhost
  shell: |
    lxc exec {{ groups['k3s_cluster'][0] }} -- cat /etc/rancher/k3s/k3s.yaml
  register: kubeconfig_content
  changed_when: false
  run_once: true

- name: Get IP of first node
  include_tasks: get_node_ip.yaml
  vars:
    node_name: "{{ groups['k3s_cluster'][0] }}"

- name: Update kubeconfig with correct server IP
  set_fact:
    updated_kubeconfig: "{{ kubeconfig_content.stdout | replace('127.0.0.1', node_ip) }}"
  run_once: true

- name: Save kubeconfig locally
  copy:
    content: "{{ updated_kubeconfig }}"
    dest: "{{ kubeconfig_path }}"
    mode: '0600'
  delegate_to: localhost
  run_once: true
