# Application metadata for Argo CD / ApplicationSet
# Phase 1: informational only – no behavioural change

name: external-secrets
path: base/security/external-secrets
namespace: security
wave: 1
env: prod
