---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile

repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts/
  - name: external-secrets
    url: https://charts.external-secrets.io/

releases:
  - name: external-secrets
    chart: external-secrets/external-secrets
    version: 1.2.0
    values:
      - values.yaml

  - name: bitwarden-access-token
    chart: bedag/raw
    version: 2.0.2
    secrets:
     - bitwarden-access-token-sops.yaml

  - name: bitwarden-store
    chart: bedag/raw
    version: 2.0.2
    values:
      - bitwarden-store.yaml
    needs:
      - bitwarden-access-token
