---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: security
      bitwardenServerSDKURL: https://bitwarden-sdk-server.security.svc.cluster.local:9998
      organizationID: 3c3e91e1-ea8a-4112-870d-b13101194ab4
      projectID: b2575a9a-5a8b-4c80-b2db-b1310119ab00
      caProvider:
        namespace: security
        type: Secret
        name: bitwarden-css-certs
        key: ca.crt
