---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile

bases:
  - ../../../clusters/environments.yaml

repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts/

releases:
  - name: coredns
    namespace: kube-system
    chart: bedag/raw
    values:
      - values.yaml.gotmpl
