---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile

bases:
  - ../../../clusters/environments.yaml

repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts/

releases:
  - name: coredns
    namespace: kube-system
    chart: bedag/raw
    values:
      - resources:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: coredns
              namespace: kube-system
              labels:
                app.kubernetes.io/managed-by: "Helm"
                k8s-app: kube-dns
              annotations:
                meta.helm.sh/release-name: "coredns"
                meta.helm.sh/release-namespace: "kube-system"
            spec:
              replicas: 3
              template:
                spec:
                  tolerations:
                    - key: "node-role.kubernetes.io/control-plane"
                      operator: "Exists"
                      effect: "NoSchedule"
                  topologySpreadConstraints:
                    - maxSkew: 1
                      topologyKey: kubernetes.io/hostname
                      whenUnsatisfiable: DoNotSchedule
                      labelSelector:
                        matchLabels:
                          k8s-app: kube-dns
          
          - apiVersion: policy/v1
            kind: PodDisruptionBudget
            metadata:
              name: coredns
              namespace: kube-system
            spec:
              minAvailable: 2
              selector:
                matchLabels:
                  k8s-app: kube-dns
