---
rawResources:
  secret:
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    spec:
      spec:
        secretStoreRef: &store
          kind: ClusterSecretStore
          name: bitwarden
        target:
          name: "{{.Release.Name}}-secret"
          creationPolicy: Owner
          template:
            data:
              secrets.yaml: |
                mqtt_user: "{{`{{ .MQTT_USER }}`}}"
                mqtt_password: "{{`{{ .MQTT_PASSWORD }}`}}"
                wifi_ssid: "{{`{{ .wifi_ssid }}`}}"
                wifi_password: "{{`{{ .wifi_password }}`}}"

        dataFrom:
          - extract:
              key: mqtt_credentials
          - extract:
              key: wifi_credentials

  github:
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    spec:
      spec:
        secretStoreRef: *store
        target:
          name: "{{.Release.Name}}-github"
        dataFrom:
          - extract:
              key: github_user
