---
resources:
  - apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: &secret esphome-secret
      labels:
        app.kubernetes.io/name: esphome
    spec:
      refreshInterval: 5m
      secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden
      target:
        name: *secret
        creationPolicy: Owner
        template:
          data:
            secrets.yaml: |
              mqtt_user: "{{ .MQTT_USER }}"
              mqtt_password: "{{ .MQTT_PASSWORD }}"
              wifi_ssid: "{{ .wifi_ssid }}"
              wifi_password: "{{ .wifi_password }}"

      dataFrom:
        - extract:
            key: mqtt_credentials
        - extract:
            key: wifi_credentials
