---
rawResources:
  externalsecret:
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    labels:
      app.kubernetes.io/name: esphome
    spec:
      spec:
        refreshInterval: 15m
        secretStoreRef:
          kind: ClusterSecretStore
          name: bitwarden
        target:
          name: esphome-secret
          creationPolicy: Owner
          template:
            data:
              secrets.yaml: |
                mqtt_user: "{{`{{ .MQTT_USER }}`}}"
                mqtt_password: "{{`{{ .MQTT_PASSWORD }}`}}"
                wifi_ssid: "{{`{{ .wifi_ssid }}`}}"
                wifi_password: "{{`{{ .wifi_password }}`}}"

        dataFrom:
          - extract:
              key: mqtt_credentials
          - extract:
              key: wifi_credentials
