---
repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts/

releases:
  - name: esphome
    chart: oci://ghcr.io/bjw-s-labs/helm/app-template
    version: 4.3.0
    values:
      - ../../../settings/common.yaml
      - values.yaml
      - externalsecret.yaml
