---
global:
  # -- Set an override for the prefix of the fullname
  nameOverride: streammaster
  # -- Set the entire name definition
  fullnameOverride:
  # -- Set additional global labels. Helm templates can be used.
  labels: {}
  # -- Set additional global annotations. Helm templates can be used.
  annotations: {}

controllers:
  streammaster:
    enabled: true
    type: deployment
    containers:
      streammaster:
        image:
          repository: senexcrenshaw/streammaster
          tag: 0.17.9
        resources:
          requests:
            cpu: 92m
            memory: 814M
            gpu.intel.com/i915: "1"
          limits:
            cpu: 915m
            memory: 1257M
            gpu.intel.com/i915: "1"

service:
  # Configure a service for the main application
  streammaster:
    controller: streammaster
    type: ClusterIP
    ports:
      http:
        port: 7095

ingress:
  streammaster:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: &host "streammaster.theclarkhome.com"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: streammaster
              port: http
    tls:
      - hosts:
          - '*.theclarkhome.com'

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: openebs-zfspv
    accessMode: ReadWriteOnce
    retain: true
    size: 1G
    globalMounts:
      - path: /root/.streammaster

  logos:
    type: persistentVolumeClaim
    storageClass: openebs-zfspv
    accessMode: ReadWriteOnce
    size: 1G
    retain: true
    globalMounts:
      - path: /root/.streammaster/tv-logos
