---
global:
  nameOverride: streammaster

# defaultPodOptions:
#   affinity:
#     nodeAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#         nodeSelectorTerms:
#           - matchExpressions:
#               - key: kubernetes.io/hostname
#                 operator: NotIn
#                 values:
#                   - golf

controllers:
  streammaster:
    enabled: true
    type: deployment
    containers:
      streammaster:
        image:
          repository: carlreid/streammaster
          tag: 0.13.0
          # repository: senexcrenshaw/streammaster
          # tag: 1.0.0
          # repository: alexphillips/streammaster
          # tag: 1.10.0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: sm123
          PGDATA: /config/DB
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_DB: StreamMaster
          BACKUP_VERSIONS_TO_KEEP: 5

        resources:
          requests:
            cpu: 10m
            memory: 670M
            # gpu.intel.com/i915: "1"  # enable if vaapi used in sm
          limits:
            # cpu: 1100m
            memory: 1572M
            # gpu.intel.com/i915: "1"  # enable if vaapi used in sm

service:
  # Configure a service for the main application
  streammaster:
    controller: streammaster
    type: ClusterIP
    ports:
      http:
        port: 7095

ingress:
  streammaster:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: &host "streammaster.theclarkhome.com"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: streammaster
              port: http
    tls:
      - hosts:
          - '*.theclarkhome.com'

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: openebs-zfspv
    accessMode: ReadWriteOnce
    retain: true
    size: 1G

  logos:
    type: persistentVolumeClaim
    storageClass: openebs-zfspv
    accessMode: ReadWriteOnce
    size: 1G
    retain: true
