---

controllers:
  multus:
    containers:
      multus:
        image:
          repository: ghcr.io/k8snetworkplumbingwg/multus-cni
          tag: v4.2.4-thick@sha256:3c20900b5381fac7f9cbbdfac8370ea10a2f6ed7fbecc678384a9db57047abb1
    initContainers:
      cni-installer:
        image:
          repository: rancher/hardened-cni-plugins
          tag: v1.9.0-build20251215@sha256:095324ab04261e82dce08dd3824563837bad246f424f3f57612e1881c63a5f80

cni:
  paths:
    config: /var/lib/rancher/k3s/agent/etc/cni/net.d
    bin: /var/lib/rancher/k3s/data/cni

  logLevel: verbose

  version: "0.3.1"

hostPaths:
  netns: /run/netns/
