---
image:
  repository: ghcr.io/external-secrets/external-secrets
  # tag: v0.19.2

installCRDs: true

serviceMonitor:
  enabled: true
  interval: 1m

certController:
  image:
    repository: ghcr.io/external-secrets/external-secrets
  serviceMonitor:
    enabled: true
    interval: 1m
webhook:

  image:
    repository: ghcr.io/external-secrets/external-secrets
  serviceMonitor:
    enabled: true
    interval: 1m

grafanaDashboard:
  enabled: true

bitwarden-sdk-server:
  enabled: true
  podAnnotations:
    secret.reloader.stakater.com/reload: 'bitwarden,bitwarden-tls-certs'
