---
apiVersions:
  - monitoring.coreos.com/v1

repositories:
  - name: traefik
    url: https://traefik.github.io/charts/

releases:
  - name: traefik
    chart: traefik/traefik
    version: 37.1.2
    values:
      - values.yaml
