---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile

helmDefaults:
  wait: true
  waitForJobs: true

bases:
  - ../../../clusters/environments.yaml

apiVersions:
  - "monitoring.coreos.com/v1/ServiceMonitor"

repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts/
  - name: external-secrets
    url: https://charts.external-secrets.io/

releases:
  # 1. Access Token Secret
  - name: bitwarden-access-token
    chart: bedag/raw
    version: 2.0.2
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    secrets:
      - bitwarden-access-token-sops.yaml

  # 2. Certificates with the "Wait" Hook
  - name: bitwarden-certs
    chart: bedag/raw
    version: 2.0.2
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    values:
      - bitwarden-certs.yaml
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "wait"
          - "--for=condition=Ready"
          - "certificate/bitwarden-tls-certs"
          - "certificate/bitwarden-css-certs"
          - "-n"
          - '{{ env "HELMFILE_NAMESPACE" }}'
          - "--timeout=300s"

  # 3. Main External Secrets Chart
  - name: external-secrets
    chart: external-secrets/external-secrets
    version: 2.4.1
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    needs:
      - bitwarden-certs
    values:
      - values.yaml

  # 4. The ClusterSecretStore
  - name: bitwarden-store
    chart: bedag/raw
    version: 2.0.2
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    values:
      - bitwarden-store.yaml
    needs:
      - bitwarden-access-token
      - external-secrets
