---
repositories:
  - name: cilium
    url: https://helm.cilium.io/

releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    version: 1.18.6
    # wait: true
    # timeout: 600
    values:
      - values.yaml
