---
- name: Detect runtime
  include_role:
    name: helpers
    tasks_from: detect_runtime

- name: Get and save kubeconfig
  include_role:
    name: helpers
    tasks_from: get_kubeconfig
  vars:
    kubeconfig_path: "{{ lookup('env', 'HOME') }}/.kube/clusters/{{ cluster_name }}.yaml"

- name: Verify kubeconfig works
  delegate_to: localhost
  shell: "kubectl --kubeconfig {{ lookup('env', 'HOME') }}/.kube/clusters/{{ cluster_name }}.yaml get nodes"
  register: verify
  changed_when: false

- name: Show cluster nodes
  debug:
    msg: "{{ verify.stdout_lines }}"