---
- name: Get and save kubeconfig
  include_role:
    name: helpers
    tasks_from: get_kubeconfig
  vars:
    kubeconfig_path: "{{ lookup('env', 'HOME') }}/.kube/clusters/{{ cluster_name }}.yaml"

- name: Set KUBECONFIG fact for future tasks
  set_fact:
    kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/clusters/{{ cluster_name }}.yaml"
  run_once: true
  delegate_to: localhost

- name: Verify cluster access
  delegate_to: localhost
  shell: "kubectl --kubeconfig {{ kubeconfig }} get nodes"
  register: nodes
  changed_when: false
  run_once: true

- name: Show cluster nodes
  debug:
    msg: "{{ nodes.stdout_lines }}"
  run_once: true
  delegate_to: localhost
