---
configuration:
  uploaderType: kopia
  # defaultVolumesToFsBackup: true
  # defaultSnapshotMoveData: true
  # features: EnableCSI
  backupStorageLocation:
    - name: idrive
      provider: aws
      bucket: velero
      credential:
        name: idrivee2-s3-credentials
        key: cloud
      config:
        region: London
        s3ForcePathStyle: true
        s3Url: https://j5o6.ldn.idrivee2-27.com
        publicUrl: https://j5o6.ldn.idrivee2-27.com
        # Disable checksumAlgorithm to avoid issues with Minio
        # https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/197
        checksumAlgorithm: ""
    - name: default
      provider: aws
      bucket: velero
      credential:
        name: minio-s3-credentials
        key: cloud
      config:
        region: London
        s3ForcePathStyle: true
        s3Url: http://foxtrot.theclarkhome.com:9000
        publicUrl: http://foxtrot.theclarkhome.com:9000
  # volumeSnapshotLocation:
  #   - name: openebs-zfspv
  #     provider: csi

snapshotsEnabled: false
# defaultVolumeSnapshotLocations: csi:seaweedfs

resources:
  requests:
    cpu: 22m
    memory: 549M
  limits:
    cpu: 997m
    memory: 1066M

deployNodeAgent: true

nodeAgent:
  resources:
    requests:
      cpu: 30m
      memory: 549M
    limits:
      cpu: 90m
      memory: 1545M

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.11.0
    volumeMounts:
      - mountPath: /target
        name: plugins
#  - name: velero-plugin-for-csi
#    image: velero/velero-plugin-for-csi:v0.5.0
#    volumeMounts:
#      - mountPath: /target
#        name: plugins

# credentials:
#   useSecret: true
#   name: cloud-credentials
#   existingSecret:
#   secretContents:
#     cloud: |
#       [default]
#       aws_access_key_id=Unwarlike3-Keenly-Colt
#       aws_secret_access_key=Choice4-Entourage-Equal

schedules:
  # idrive storage
  daily-idrive:
    disabled: false
    schedule: "@daily"
    useOwnerReferencesInBackup: true
    template:
      ttl: "168h"
      storageLocation: idrive
  weekly-idrive:
    disabled: false
    schedule: "@weekly"
    useOwnerReferencesInBackup: true
    template:
      ttl: "672h"
      storageLocation: idrive
  monthly-idrive:
    disabled: false
    schedule: "@monthly"
    useOwnerReferencesInBackup: true
    template:
      ttl: "2190h"
      storageLocation: idrive
  # default storage
  hourly-minio:
    disabled: false
    schedule: "@hourly"
    useOwnerReferencesInBackup: true
    template:
      ttl: "24h"
      storageLocation: default
  daily-minio:
    disabled: false
    schedule: "@daily"
    useOwnerReferencesInBackup: true
    template:
      ttl: "168h"
      storageLocation: default
  weekly-minio:
    disabled: false
    schedule: "@weekly"
    useOwnerReferencesInBackup: true
    template:
      ttl: "672h"
      storageLocation: default
  monthly-minio:
    disabled: false
    schedule: "@monthly"
    useOwnerReferencesInBackup: true
    template:
      ttl: "2190h"
      storageLocation: default


metrics:
  enabled: true
  scrapeInterval: 30s
  scrapeTimeout: 10s

  # service metdata if metrics are enabled
  service:
    annotations: {}
    labels: {}

  # Pod annotations for Prometheus
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: "/metrics"

  serviceMonitor:
    autodetect: false
    enabled: true
    annotations: {}
    additionalLabels: {}

  nodeAgentPodMonitor:
    autodetect: false
    enabled: true
    annotations: {}
    additionalLabels: {}

  prometheusRule:
    autodetect: false
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
    spec:
      - alert: VeleroLastBackupFailed
        annotations:
          # yamllint disable-line rule:line-length
          message: Velero backup {{ $labels.schedule }} {{ $labels.namespace }} failed last backups
        expr: velero_backup_last_status{schedule!=""} != 1
        for: 15m
        labels:
          severity: warning

      - alert: VeleroBackupItemsFailed
        annotations:
          # yamllint disable-line rule:line-length
          message: Velero backup {{ $labels.schedule }} {{ $labels.namespace }} has {{ $value }} failed items
        expr: velero_backup_items_errors{schedule!=""} != 0
        for: 15m
        labels:
          severity: warning

      # - alert: VeleroBackupPartialFailures
      #   # yamllint disable-line rule:line-length
      #   annotations:
      #     # yamllint disable-line rule:line-length
      #     message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups.
      #   # yamllint disable rule:line-length
      #   expr: |-
      #     velero_backup_partial_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
      #   # yamllint enable rule:line-length
      #   for: 15m
      #   labels:
      #     severity: warning
      # - alert: VeleroBackupFailures
      #   annotations:
      #     # yamllint disable-line rule:line-length
      #     message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} failed backups.
      #   # yamllint disable rule:line-length
      #   expr: |-
      #     velero_backup_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
      #   # yamllint enable rule:line-length
      #   for: 15m
      #   labels:
      #     severity: warning

# extraObjects:
#   velero:
#     apiVersion: autoscaling.k8s.io/v1
#     kind: VerticalPodAutoscaler
#     metadata:
#       namespace: velero
#       name: velero-vpa
#       #labels:
#       #  app.kubernetes.io/name: velero
#     spec:
#       targetRef:
#         apiVersion: "apps/v1"
#         kind:       Deployment
#         name:       velero
#       updatePolicy:
#         updateMode: "Auto"
