# yaml-language-server: $schema=https://json.schemastore.org/helmfile
---
bases:
  - ../../../clusters/environments.yaml

releases:
  - name: kyverno
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    chart: oci://ghcr.io/kyverno/charts/kyverno
    version: 3.7.1
    values:
      - values.yaml

  - name: kyverno-policies-custom
    chart: ./policies
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    needs:
      - kyverno
    values:
      - validationFailureAction: Enforce
