---
bases:
  - ../../../clusters/environments.yaml

repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts/

releases:
  - name: kyverno
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    chart: oci://ghcr.io/kyverno/charts/kyverno
    version: 3.7.1
    values:
      - values.yaml

  - name: kyverno-set-pv-to-retain-on-keep-policy
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    chart: bedag/raw
    version: 2.0.2
    needs:
      - kyverno
    values:
      - set-pv-to-retain-on-keep.yaml

  - name: remove-cpu-limits-requests
    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
    chart: bedag/raw
    version: 2.0.2
    needs:
      - kyverno
    values:
      - remove-cpu-limits-requests.yaml

#  - name: propagate-topology-spread
#    namespace: '{{ env "HELMFILE_NAMESPACE" }}'
#    chart: bedag/raw
#    version: 2.0.2
#    needs:
#      - kyverno
#    values:
#      - propagate-topology-spread.yaml
