---
releases:
  - name: kube-prometheus-stack
    chart: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
    version: 77.11.0
    values:
      - values.yaml
      - externalsecret.yaml
