---
# TODO add init cintainer or similar to load config

global:
  nameOverride: predbat

controllers:
  predbat:
    annotations:
      reloader.stakater.com/auto: "true"
    enabled: true
    type: deployment

    defaultContainerOptions:
      resources:
        requests:
          cpu: 10m
          memory: 94M
        limits:
          memory: 256M

    containers:
      app:
        image:
          repository: nipar44/predbat_addon
          tag: v8.25.14@sha256:afcf55fa0f65e081ca7e11c34324e94ce20ad2c508733c5ad723479fd9f37b30
        env:
          TZ: "Europe/London"
      code-server:
        dependsOn: app
        image:
          repository: ghcr.io/coder/code-server
          # yamllint disable-line rule:line-length
          tag: 4.105.1@sha256:2d48970bd2084aa34a522d772b6a437981ea80407465b3bf7958553985c570e1
        env:
          TZ: "Europe/London"
        args:
          - --auth=none
          - --disable-telemetry
          - --disable-update-check
          - --user-data-dir
          - /config/.code-server
          - --extensions-dir
          - /config/.code-server
          - --port
          - "12321"
          - /config
        securityContext:
          runAsUser: 0

service:
  app:
    forceRename: "{{.Release.Name}}"
    ports:
      http:
        port: &http_port 5052
  code-server:
    ports:
      http:
        port: &code-server_port 12321

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: openebs-zfspv
    accessMode: ReadWriteOnce
    retain: true
    size: 250Mi
    globalMounts:
      - path: /config

rawResources:
  middleware:
    apiVersion: traefik.io/v1alpha1
    kind: Middleware
    spec:
      spec:
        stripPrefixRegex:
          regex:
            - "^/code/"

  ingress:
    enabled: true
    kind: IngressRoute
    apiVersion: traefik.io/v1alpha1
    annotations:
      kubernetes.io/ingress.class: traefik-external
    spec:
      spec:
        entryPoints:
          - websecure
        routes:
          - kind: Rule
            # yamllint disable-line rule:line-length
            match: Host(`{{.Release.Name}}.{{.Values.global.domain}}`) && PathPrefix(`/`)
            priority: 10
            services:
              - name: "{{.Release.Name}}"
                port: *http_port
          - kind: Rule
            # yamllint disable-line rule:line-length
            match: Host(`{{.Release.Name}}.{{.Values.global.domain}}`) && PathRegexp(`^/code/.*`)
            priority: 11
            services:
              - name: "{{.Release.Name}}-code-server"
                port: *code-server_port
            middlewares:
              - name: "{{.Release.Name}}-middleware"
        tls: {}
