resources:
  - apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: &secret openwebui-env
    spec:
      refreshInterval: 1h
      secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden
      target:
        name: *secret
        creationPolicy: Owner
        template:
          engineVersion: v2
          data:
            # Can be a comma separated list. Keep order the same as for OPENAI_API_BASE_URLS
            OPENAI_API_KEYS: '{{ (.openrouter | fromYaml).openwebui}}'
            TAVILY_API_KEY: '{{ (.tavily | fromYaml).openwebui }}'

      data:
        - secretKey: openrouter
          remoteRef:
            key: openrouter_api_key
        - secretKey: tavily
          remoteRef:
            key: tavily_api_key
