resources:
  - apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: &secret openwebui-env
    spec:
      refreshInterval: 1h
      secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden
      target:
        name: *secret
        creationPolicy: Owner
        template:
          engineVersion: v2
          data:
            OPENAI_API_KEY: '{{ (.openrouter | fromYaml).openwebui }}'
            TAVILY_API_KEY: '{{ (.tavily | fromYaml).openwebui }}'
      data:
        - secretKey: openrouter
          remoteRef:
            key: openrouter_api_key
        - secretKey: tavily
          remoteRef:
            key: tavily_api_key
