---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile

bases:
  - ../../../clusters/environments.yaml

repositories:
  - name: open-webui
    url: https://helm.openwebui.com

releases:
  - name: open-webui
    chart: open-webui/open-webui
    version: "16.6.0"
    namespace: '{{ env "HELMFILE_NAMESPACE" | default "default" }}'
    values:
      - values.yaml.gotmpl
