resources:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-secret
      data:
        admin.password: ENC[AES256_GCM,data:brYi9u1BM/vrXh/0BMofWtlKnEg6I9TB3AObMWSDz+9eQ7o9cAyo00DwllffTIPZbejjnkKS4tZTTVaeZAtmm566mORgiUpLiYAozknWZ6s=,iv:jtVNhdw75QerEMk9SoW1wO2z4YZCQhT+7oDzHlNcBjQ=,tag:EBusEuuzyza4uFXtIFm71w==,type:str]
        server.secretkey: ENC[AES256_GCM,data:+EPjHIdUFrHG06GUznC8AiE0FuximmYQGNWtdfaBYQTwdtIa4AZ6AU9ZQFN2Gob+gfv4g4DPQ+o8TEhI,iv:Q4WaaF9kFwq01hTHcucy8RAwRNNvq7vAK19BotV45+4=,tag:kWodvY5hulqFcqAbxC9D/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1V2RlamxrenkySTFUT1lC
            MlAzRmpTTGZaS040K2dyYTZ2cHhxQkhXL2hRCnlZdUJHbENGMlJmMjhWT0cyenNq
            ZzNsU0FHYWF1aldWZWM0RnNxQ2JvMDgKLS0tIG5ZSDYvT21DRnE3U2VZOW1vYlVC
            WmM5TnBmYXI5M08xeEZKaGRXeUI1MTgKNewdFCw2En7ya+QWI1uVNCz5FY+gIFHo
            5FXRLcQci5CfkMUSFGWoPzscfACZmfjm4FLQfkxbhlSyj9+041mvrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kxa0h4zt4txae7wdjy5pck2jvzalmg4mrryuw3qqpzp2jl44n3tqmd0vyp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWXNSNEY0ZVNWMnVKOG1O
            aVpxL3MveWN3L0ZHZnZFK1dqT0tFVUNEK1hJCnB2QkV0cWZQZVNrRElhUHlNbWpF
            MmtDZ0s5aHhrcHlSMHA5ZDNJNFlrSVEKLS0tIGc1N3lEQ1czay9OK0hRSWFEeCti
            blRPUDVuMmNCaGhDUDBQRzNOdkphMnMKw7G023208dQrdT83pCGDp74AGWvBxYp6
            wSXwrLqc8lYTftqj359uOIXrOjSe0iIEqWVZ91f+MTIepDcec85uoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdsld93s2qul4z7rrqkj7755gvptg09z9n4guefrcvqjcank9uestl7zfc
    encrypted_regex: ^(data|stringData|configFile)$
    lastmodified: "2026-04-05T10:48:05Z"
    mac: ENC[AES256_GCM,data:dJpUGjdh73DqYkFkZeZDaWd+soU4or96gEFC6Nn/Hj+eD/5H7LuI/NSfA5i4THyJWEEBFHUo4ESVN3VRZRpCBcbBC2TRAtHN0HncJH38UXO1Cz/WAdf9UHXwEAKGuYawQ5j2pSyFt1SuIEGUBggFW49Ko9VA9ozHd+h9WaTWOog=,iv:KKFXlu65UxhHxJjeCGG+fPNiqA15nJJVfYp1vXdBpc4=,tag:hvddVFiIvVf8PUjb+AXE+g==,type:str]
    version: 3.12.2
