---
bases:
  - ../../../clusters/environments.yaml

repositories:
  - name: descheduler
    url: https://kubernetes-sigs.github.io/descheduler

releases:
  - name: descheduler
    chart: descheduler/descheduler
    version: "0.36.0"
    namespace: '{{ env "helmfile_namespace" | default "kube-system" }}'
    values:
      - values.yaml
