---
extraManifests:
  - |
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: grafana-admin
      labels:
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: {{.Release.Name}}
        app.kubernetes.io/part-of: {{.Release.Name}}
        app.kubernetes.io/name: "{{.Release.Name}}-grafana-admin"
    spec:
      refreshInterval: 15m
      secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden
      target:
        name: grafana-admin
        creationPolicy: Owner
      dataFrom:
        - extract:
            key: grafana_admin
