{{- range $path, $_ :=  .Files.Glob "custom/*.yaml" }}
---
{{- $policy := $.Files.Get $path | fromYaml -}}
{{- $baseMetadata := dict 
    "labels" (include "kyverno-policies.labels" $ | fromYaml)
{{- $metadata := merge ($policy.metadata | default (dict)) $baseMetadata -}}

{{- $_ := set $policy "metadata" $metadata -}}
{{- $policy | toYaml }}
{{- end }}
