---
repositories:
- name: kyverno
  url: https://kyverno.github.io/kyverno/
- name: bedag
  url: https://bedag.github.io/helm-charts/

releases:
- name: kyverno
  chart: kyverno/kyverno
  version: 3.2.6
  values:
  - values.yaml

- name: kyverno-extra-manifests
  chart: bedag/raw
  version: 1.1.0
  values:
  - backup-all-volumes.yaml
