---
controllers:
  qbittorrent:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/home-operations/qbittorrent
          tag: 5.1.2@sha256:31ac39705e31f7cdcc04dc46c1c0b0cdf8dc6f9865d4894efc097a33adc41524
        env:
          QBT_WEBUI_PORT: &port 8080
          QBT_TORRENTING_PORT: 51478
          TZ: Europe/London
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/v2/app/version
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 10

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: {drop: ["ALL"]}
        resources:
          requests:
            cpu: 22m
            memory: 4.5G
          limits:
            memory: 6.5G

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 3001
    runAsGroup: 513
    fsGroup: 513
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    forceRename: "{{.Release.Name}}"
    ports:
      http:
        port: *port

ingress:
  app:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts: &hosts
      - host: "{{.Release.Name}}.{{.Values.global.domain}}"
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - "*.{{.Values.global.domain}}"

persistence:
  config:
    enabled: true
    retain: true
    storageClass: openebs-zfspv
    accessMode: ReadWriteOnce
    size: 1Gi
  data:
    enabled: true
    type: nfs
    server: 10.58.0.12
    path: /srv/media
    globalMounts:
      - path: /data
  tmp:
    type: emptyDir
