---
image:
  repository: lscr.io/linuxserver/qbittorrent
  tag: 5.1.2@sha256:884b9b6e9c6467d9c1fb16551e03cb1f66ad32c412ce4bb492e206e0bd0f55b5

dnsPolicy: ClusterFirst

env:
  TZ: Europe/London
  UMASK: "002"
  PUID: "3001"
  PGID: "513"

service:
  qbittorrent:
    ports:
      https:
        port: 8080

ingress:
  qbittorrent:
    enabled: true
    ingressClass: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: "qbittorrent.theclarkhome.com"
        paths:
          - path: /
            backend:
              name: qbittorrent
              service:
                port: 8080
    tls:
      - hosts:
          - "*.theclarkhome.com"

persistence:
  config:
    enabled: true
    retain: true
    storageClass: openebs-zfspv
  data:
    enabled: true
    type: nfs
    server: 10.58.0.12
    path: /srv/media

resources:
  requests:
    cpu: 22m
    memory: 4.5G
  limits:
    # cpu: 29m
    memory: 6.5G
