---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile

bases:
  - ../../../common/base.yaml

repositories:
  - name: bjw-s-labs
    url: https://bjw-s-labs.github.io/helm-charts

releases:
  - name: dispatcharr
    chart: bjw-s-labs/app-template
    version: 5.2.1
    inherit:
    - template: namespace
    - template: vpn
    values:
      - values.yaml.gotmpl
