---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-5.0.0/charts/library/common/values.schema.json

controllers:
  dispatcharr:
    enabled: true
    type: deployment
    containers:
      app:
        image:
          repository: ghcr.io/dispatcharr/dispatcharr
          tag: 0.26.0@sha256:9275b0c1f5319a84b412af6839a1364ef25b61d8d6ff0d2130a6c2b2504a8b07
        env:
          dispatcharr_env: aio
          redis_host: localhost
          celery_broker_url: redis://localhost:6379/0
          dispatcharr_log_level: info
        resources:
          requests:
            cpu: 400m
            memory: 1658Mi
            # enable gpu if ffmpeg profile being used
            # gpu.intel.com/i915: "1"
          limits:
            memory: 2Gi
            # enable gpu if ffmpeg profile being used
            # gpu.intel.com/i915: "1"

service:
  # Configure a service for the main application
  app:
    type: ClusterIP
    ports:
      http:
        port: 9191

persistence:
  data:
    type: persistentVolumeClaim
    storageClass: longhorn
    accessMode: ReadWriteOnce
    retain: true
    size: 2Gi
