---

controllers:
  dispatcharr:
    enabled: true
    type: deployment
    containers:
      app:
        image:
          repository: ghcr.io/dispatcharr/dispatcharr
          tag: 0.24.0@sha256:c9920ece0dd653c12ac251aa406351a3006043200f02054472d34c417e365190
        env:
          dispatcharr_env: aio
          redis_host: localhost
          celery_broker_url: redis://localhost:6379/0
          dispatcharr_log_level: info
        resources:
          requests:
            cpu: 400m
            memory: 1658Mi
            # enable gpu if ffmpeg profile being used
            # gpu.intel.com/i915: "1"
          limits:
            memory: 2Gi
            # enable gpu if ffmpeg profile being used
            # gpu.intel.com/i915: "1"

service:
  # Configure a service for the main application
  app:
    type: ClusterIP
    ports:
      http:
        port: 9191

persistence:
  data:
    type: persistentVolumeClaim
    storageClass: openebs-zfspv
    accessMode: ReadWriteOnce
    retain: true
    size: 2Gi
