---
name: Validate Renovate Config

on:
  pull_request:
    paths:
      - 'renovate/**'
      - '.renovate/**'
  push:
    branches:
      - main
    paths:
      - 'renovate/**'
      - '.renovate/**'
  workflow_dispatch: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate:latest@sha256:bed8301bb7f38a2a4b95f24ede868db4f5cc1a487ed223055a7d5a226d9ec374
      options: --user root
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - run: renovate-config-validator --strict
