---
name: Validate Renovate Config

on:
  pull_request:
    paths:
      - 'renovate/**'
      - '.renovate/**'
  push:
    branches:
      - main
    paths:
      - 'renovate/**'
      - '.renovate/**'
  workflow_dispatch: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    container: renovate/renovate:latest
    steps:
      - uses: actions/checkout@v4
      - run: renovate-config-validator --strict
