---
name: Validate Renovate Config

on:
  pull_request:
    paths:
      - 'renovate/**'
      - '.renovate/**'
  push:
    branches:
      - main
    paths:
      - 'renovate/**'
      - '.renovate/**'
  workflow_dispatch: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate:latest@sha256:2c801b47ce82c349453e554188abe4fa0b51bde333cfea54e67ad8a88d525087
      options: --user root
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: renovate-config-validator --strict
