---
repositories:
  - name: geek-cookbook
    url: https://geek-cookbook.github.io/charts/

releases:
  - name: appdaemon
    chart: geek-cookbook/appdaemon
    version: 8.4.2
    values:
      - values.yaml
